export interface Language {
  code: string;
  hreflang: string;
  label: string;
  nativeLabel: string;
  dir: "ltr" | "rtl";
  flag: string;
}

export const SUPPORTED_LANGUAGES: Language[] = [
  { code: "en", hreflang: "en", label: "English", nativeLabel: "English", dir: "ltr", flag: "🇺🇸" },
  { code: "es", hreflang: "es", label: "Spanish", nativeLabel: "Español", dir: "ltr", flag: "🇪🇸" },
  { code: "ar", hreflang: "ar", label: "Arabic", nativeLabel: "العربية", dir: "rtl", flag: "🇸🇦" },
  { code: "hi", hreflang: "hi", label: "Hindi", nativeLabel: "हिंदी", dir: "ltr", flag: "🇮🇳" },
  { code: "fr", hreflang: "fr", label: "French", nativeLabel: "Français", dir: "ltr", flag: "🇫🇷" },
  { code: "pt", hreflang: "pt", label: "Portuguese", nativeLabel: "Português", dir: "ltr", flag: "🇧🇷" },
];

export const LANG_CODES = SUPPORTED_LANGUAGES.map(l => l.code);
export const NON_DEFAULT_LANG_CODES = LANG_CODES.filter(c => c !== "en");

export function getLang(code: string): Language {
  return SUPPORTED_LANGUAGES.find(l => l.code === code) || SUPPORTED_LANGUAGES[0];
}

export function detectBrowserLang(): string {
  const nav = typeof navigator !== "undefined" ? navigator : null;
  if (!nav) return "en";
  const preferred = (nav.language || "en").split("-")[0].toLowerCase();
  return NON_DEFAULT_LANG_CODES.includes(preferred) ? preferred : "en";
}

export function getLangFromPath(pathname: string): { lang: string; basePath: string } {
  const match = pathname.match(/^\/(es|ar|hi|fr|pt)(\/.*)?$/);
  if (match) {
    return { lang: match[1], basePath: match[2] || "/" };
  }
  return { lang: "en", basePath: pathname };
}

export function buildLangPath(lang: string, basePath: string): string {
  if (lang === "en") return basePath;
  const normalizedBase = basePath.startsWith("/") ? basePath : `/${basePath}`;
  return `/${lang}${normalizedBase === "/" ? "" : normalizedBase}`;
}

export const UI_TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    home: "Home",
    allTools: "All Tools",
    blog: "Blog",
    pdfToWord: "PDF to Word",
    merge: "Merge PDF",
    compress: "Compress",
    languageSwitcher: "Language",
    bannerText: "This page is available in",
    bannerSwitch: "Switch to",
    bannerDismiss: "Dismiss",
    uploadYourFiles: "Upload Your Files",
    dropFilesHere: "Drop your files here!",
    releaseToUpload: "Release to upload",
    tapToSelectFile: "Tap to select your file",
    tapToSelectFiles: "Tap to select up to {n} files",
    selectFile: "Select File",
    selectFiles: "Select Files",
    selectedFile: "Selected File",
    selectedFiles: "Selected Files ({n}/{max})",
    addMore: "Add More",
    clearAll: "Clear All",
    secure: "Secure",
    fast: "Fast",
    free: "Free",
    hundredFree: "100% Free",
    noLimits: "No Limits",
    noHiddenCosts: "No hidden costs",
    sslEncrypted: "SSL encrypted",
    cloudPowered: "Cloud powered",
    unlimitedUse: "Unlimited use",
    popularTools: "Popular Tools",
    menu: "Menu",
    openMenu: "Open menu",
    convertFromPdf: "Convert from PDF",
    convertToPdf: "Convert to PDF",
    editPdf: "Edit PDF",
    utilityTools: "Utility Tools",
    compressPdf: "Compress PDF",
    freeToolsCount: "43+ Free PDF Tools",
    heroBadge: "43+ Free PDF Tools - No Registration Required",
    heroTitle: "Professional PDF Tools",
    heroFree: "100% Free Online",
    heroSubtitle: "Convert, merge, compress, and edit PDF files instantly. Trusted by millions of users worldwide.",
    heroDropFile: "Drop your file here or click to upload",
    heroChooseTool: "Then choose what you want to do with it",
    splitPdf: "Split PDF",
    whatWouldYouLikeToDo: "What would you like to do?",
    viewAllTools: "View All 43+ Tools",
    featuredTools: "Featured Tools",
    mostPopular: "Most Popular",
    allPdfTools: "All PDF Tools",
    completeToolkit: "Complete Toolkit",
    allPdfToolsSubtitle: "Choose from 43+ professional tools for all your PDF needs",
    simpleProcess: "Simple Process",
    howItWorks: "How It Works",
    howItWorksSubtitle: "Three simple steps to transform your PDF files",
    step1Title: "Choose Your Tool",
    step2Title: "Upload Your File",
    step3Title: "Download Result",
    whyChooseUs: "Why Choose Us",
    whyPdfHub24: "Why PDF HUB 24?",
    whyChooseSubtitle: "Trusted by users worldwide for fast, secure, and reliable PDF processing",
    viewAllArticles: "View All Articles",
    featuredLabel: "Featured",
    useTool: "Use",
        gdprCompliant: "GDPR Compliant",
    noRegistration: "No Registration",
    showAllTools: "Show all {n} tools",
    showFewerTools: "Show fewer tools",
  },
  es: {
    home: "Inicio",
    allTools: "Todas las herramientas",
    blog: "Blog",
    pdfToWord: "PDF a Word",
    merge: "Unir PDF",
    compress: "Comprimir",
    languageSwitcher: "Idioma",
    bannerText: "Esta página está disponible en",
    bannerSwitch: "Cambiar a",
    bannerDismiss: "Cerrar",
    uploadYourFiles: "Sube tus archivos",
    dropFilesHere: "¡Suelta tus archivos aquí!",
    releaseToUpload: "Suelta para subir",
    tapToSelectFile: "Toca para seleccionar tu archivo",
    tapToSelectFiles: "Toca para seleccionar hasta {n} archivos",
    selectFile: "Seleccionar archivo",
    selectFiles: "Seleccionar archivos",
    selectedFile: "Archivo seleccionado",
    selectedFiles: "Archivos seleccionados ({n}/{max})",
    addMore: "Añadir más",
    clearAll: "Limpiar todo",
    secure: "Seguro",
    fast: "Rápido",
    free: "Gratis",
    hundredFree: "100% Gratis",
    noLimits: "Sin límites",
    noHiddenCosts: "Sin costos ocultos",
    sslEncrypted: "Cifrado SSL",
    cloudPowered: "Nube potente",
    unlimitedUse: "Uso ilimitado",
    popularTools: "Herramientas populares",
    menu: "Menú",
    openMenu: "Abrir menú",
    convertFromPdf: "Convertir desde PDF",
    convertToPdf: "Convertir a PDF",
    editPdf: "Editar PDF",
    utilityTools: "Herramientas de utilidad",
    compressPdf: "Comprimir PDF",
    freeToolsCount: "43+ herramientas PDF gratis",
    heroBadge: "43+ herramientas PDF gratuitas - Sin registro",
    heroTitle: "Herramientas PDF profesionales",
    heroFree: "100% Gratis Online",
    heroSubtitle: "Convierte, une, comprime y edita archivos PDF al instante. Confiado por millones de usuarios en todo el mundo.",
    heroDropFile: "Suelta tu archivo aquí o haz clic para subir",
    heroChooseTool: "Luego elige qué quieres hacer con él",
    splitPdf: "Dividir PDF",
    whatWouldYouLikeToDo: "¿Qué te gustaría hacer?",
    viewAllTools: "Ver todas las 43+ herramientas",
    featuredTools: "Herramientas destacadas",
    mostPopular: "Más populares",
    allPdfTools: "Todas las herramientas PDF",
    completeToolkit: "Kit completo",
    allPdfToolsSubtitle: "Elige entre 43+ herramientas profesionales para todas tus necesidades PDF",
    simpleProcess: "Proceso sencillo",
    howItWorks: "Cómo funciona",
    howItWorksSubtitle: "Tres sencillos pasos para transformar tus archivos PDF",
    step1Title: "Elige tu herramienta",
    step2Title: "Sube tu archivo",
    step3Title: "Descarga el resultado",
    whyChooseUs: "¿Por qué elegirnos?",
    whyPdfHub24: "¿Por qué PDF HUB 24?",
    whyChooseSubtitle: "Confiado por usuarios en todo el mundo para un procesamiento de PDF rápido, seguro y confiable",
    viewAllArticles: "Ver todos los artículos",
    featuredLabel: "Destacado",
    useTool: "Usar",
        gdprCompliant: "Cumple con GDPR",
    noRegistration: "Sin registro",
    showAllTools: "Mostrar todas las {n} herramientas",
    showFewerTools: "Mostrar menos herramientas",
  },
  ar: {
    home: "الرئيسية",
    allTools: "جميع الأدوات",
    blog: "المدونة",
    pdfToWord: "PDF إلى Word",
    merge: "دمج PDF",
    compress: "ضغط",
    languageSwitcher: "اللغة",
    bannerText: "هذه الصفحة متاحة باللغة",
    bannerSwitch: "التبديل إلى",
    bannerDismiss: "إغلاق",
    uploadYourFiles: "قم برفع ملفاتك",
    dropFilesHere: "أسقط ملفاتك هنا!",
    releaseToUpload: "أطلق للرفع",
    tapToSelectFile: "انقر لاختيار ملفك",
    tapToSelectFiles: "انقر لاختيار حتى {n} ملفات",
    selectFile: "اختر ملفاً",
    selectFiles: "اختر ملفات",
    selectedFile: "الملف المختار",
    selectedFiles: "الملفات المختارة ({n}/{max})",
    addMore: "أضف المزيد",
    clearAll: "مسح الكل",
    secure: "آمن",
    fast: "سريع",
    free: "مجاني",
    hundredFree: "100% مجاني",
    noLimits: "بلا حدود",
    noHiddenCosts: "لا تكاليف خفية",
    sslEncrypted: "مشفر بـ SSL",
    cloudPowered: "مدعوم بالسحابة",
    unlimitedUse: "استخدام غير محدود",
    popularTools: "الأدوات الشائعة",
    menu: "القائمة",
    openMenu: "فتح القائمة",
    convertFromPdf: "التحويل من PDF",
    convertToPdf: "التحويل إلى PDF",
    editPdf: "تعديل PDF",
    utilityTools: "أدوات المرافق",
    compressPdf: "ضغط PDF",
    freeToolsCount: "أكثر من 43 أداة PDF مجانية",
    heroBadge: "أكثر من 43 أداة PDF مجانية - بدون تسجيل",
    heroTitle: "أدوات PDF احترافية",
    heroFree: "100% مجاني عبر الإنترنت",
    heroSubtitle: "حوّل ملفات PDF ودمجها واضغطها وعدّلها على الفور. موثوق به من قبل ملايين المستخدمين حول العالم.",
    heroDropFile: "أسقط ملفك هنا أو انقر للرفع",
    heroChooseTool: "ثم اختر ما تريد فعله به",
    splitPdf: "تقسيم PDF",
    whatWouldYouLikeToDo: "ماذا تريد أن تفعل؟",
    viewAllTools: "عرض جميع الأدوات 43+",
    featuredTools: "الأدوات المميزة",
    mostPopular: "الأكثر شعبية",
    allPdfTools: "جميع أدوات PDF",
    completeToolkit: "مجموعة أدوات كاملة",
    allPdfToolsSubtitle: "اختر من بين 43+ أداة احترافية لجميع احتياجاتك من PDF",
    simpleProcess: "عملية بسيطة",
    howItWorks: "كيف يعمل",
    howItWorksSubtitle: "ثلاث خطوات بسيطة لتحويل ملفات PDF الخاصة بك",
    step1Title: "اختر أداتك",
    step2Title: "ارفع ملفك",
    step3Title: "تنزيل النتيجة",
    whyChooseUs: "لماذا تختارنا",
    whyPdfHub24: "لماذا PDF HUB 24؟",
    whyChooseSubtitle: "موثوق به من قبل المستخدمين في جميع أنحاء العالم لمعالجة PDF السريعة والآمنة والموثوقة",
    viewAllArticles: "عرض جميع المقالات",
    featuredLabel: "مميز",
    useTool: "استخدم",
        gdprCompliant: "متوافق مع GDPR",
    noRegistration: "بدون تسجيل",
    showAllTools: "عرض جميع الأدوات {n}",
    showFewerTools: "عرض أدوات أقل",
  },
  hi: {
    home: "होम",
    allTools: "सभी टूल्स",
    blog: "ब्लॉग",
    pdfToWord: "PDF से Word",
    merge: "PDF जोड़ें",
    compress: "कम्प्रेस",
    languageSwitcher: "भाषा",
    bannerText: "यह पृष्ठ उपलब्ध है",
    bannerSwitch: "स्विच करें",
    bannerDismiss: "बंद करें",
    uploadYourFiles: "अपनी फ़ाइलें अपलोड करें",
    dropFilesHere: "यहाँ फ़ाइलें छोड़ें!",
    releaseToUpload: "अपलोड करने के लिए छोड़ें",
    tapToSelectFile: "फ़ाइल चुनने के लिए टैप करें",
    tapToSelectFiles: "{n} फ़ाइलें चुनने के लिए टैप करें",
    selectFile: "फ़ाइल चुनें",
    selectFiles: "फ़ाइलें चुनें",
    selectedFile: "चुनी गई फ़ाइल",
    selectedFiles: "चुनी गई फ़ाइलें ({n}/{max})",
    addMore: "और जोड़ें",
    clearAll: "सब हटाएं",
    secure: "सुरक्षित",
    fast: "तेज़",
    free: "मुफ़्त",
    hundredFree: "100% मुफ़्त",
    noLimits: "कोई सीमा नहीं",
    noHiddenCosts: "कोई छुपी लागत नहीं",
    sslEncrypted: "SSL एन्क्रिप्टेड",
    cloudPowered: "क्लाउड पावर्ड",
    unlimitedUse: "असीमित उपयोग",
    popularTools: "लोकप्रिय टूल्स",
    menu: "मेनू",
    openMenu: "मेनू खोलें",
    convertFromPdf: "PDF से कन्वर्ट करें",
    convertToPdf: "PDF में कन्वर्ट करें",
    editPdf: "PDF संपादित करें",
    utilityTools: "उपयोगिता टूल्स",
    compressPdf: "PDF कम्प्रेस",
    freeToolsCount: "43+ मुफ़्त PDF टूल्स",
    heroBadge: "43+ मुफ़्त PDF टूल्स - कोई पंजीकरण नहीं",
    heroTitle: "प्रोफेशनल PDF टूल्स",
    heroFree: "100% मुफ़्त ऑनलाइन",
    heroSubtitle: "PDF फ़ाइलें तुरंत कन्वर्ट, मर्ज, कम्प्रेस और एडिट करें। दुनिया भर के लाखों उपयोगकर्ताओं द्वारा विश्वसनीय।",
    heroDropFile: "यहाँ फ़ाइल छोड़ें या अपलोड करने के लिए क्लिक करें",
    heroChooseTool: "फिर चुनें कि आप इसके साथ क्या करना चाहते हैं",
    splitPdf: "PDF विभाजित करें",
    whatWouldYouLikeToDo: "आप क्या करना चाहते हैं?",
    viewAllTools: "सभी 43+ टूल्स देखें",
    featuredTools: "विशेष टूल्स",
    mostPopular: "सबसे लोकप्रिय",
    allPdfTools: "सभी PDF टूल्स",
    completeToolkit: "पूर्ण टूलकिट",
    allPdfToolsSubtitle: "आपकी सभी PDF जरूरतों के लिए 43+ प्रोफेशनल टूल्स में से चुनें",
    simpleProcess: "सरल प्रक्रिया",
    howItWorks: "यह कैसे काम करता है",
    howItWorksSubtitle: "आपकी PDF फ़ाइलों को बदलने के लिए तीन सरल चरण",
    step1Title: "अपना टूल चुनें",
    step2Title: "अपनी फ़ाइल अपलोड करें",
    step3Title: "परिणाम डाउनलोड करें",
    whyChooseUs: "हमें क्यों चुनें",
    whyPdfHub24: "PDF HUB 24 क्यों?",
    whyChooseSubtitle: "तेज़, सुरक्षित और विश्वसनीय PDF प्रोसेसिंग के लिए दुनिया भर के उपयोगकर्ताओं द्वारा विश्वसनीय",
    viewAllArticles: "सभी लेख देखें",
    featuredLabel: "विशेष",
    useTool: "उपयोग करें",
        gdprCompliant: "GDPR अनुपालित",
    noRegistration: "कोई पंजीकरण नहीं",
    showAllTools: "सभी {n} टूल्स दिखाएं",
    showFewerTools: "कम टूल्स दिखाएं",
  },
  fr: {
    home: "Accueil",
    allTools: "Tous les outils",
    blog: "Blog",
    pdfToWord: "PDF en Word",
    merge: "Fusionner PDF",
    compress: "Compresser",
    languageSwitcher: "Langue",
    bannerText: "Cette page est disponible en",
    bannerSwitch: "Passer à",
    bannerDismiss: "Fermer",
    uploadYourFiles: "Téléchargez vos fichiers",
    dropFilesHere: "Déposez vos fichiers ici !",
    releaseToUpload: "Relâchez pour télécharger",
    tapToSelectFile: "Touchez pour sélectionner votre fichier",
    tapToSelectFiles: "Touchez pour sélectionner jusqu'à {n} fichiers",
    selectFile: "Sélectionner un fichier",
    selectFiles: "Sélectionner des fichiers",
    selectedFile: "Fichier sélectionné",
    selectedFiles: "Fichiers sélectionnés ({n}/{max})",
    addMore: "Ajouter plus",
    clearAll: "Tout effacer",
    secure: "Sécurisé",
    fast: "Rapide",
    free: "Gratuit",
    hundredFree: "100% Gratuit",
    noLimits: "Sans limites",
    noHiddenCosts: "Aucun frais caché",
    sslEncrypted: "Chiffrement SSL",
    cloudPowered: "Cloud puissant",
    unlimitedUse: "Utilisation illimitée",
    popularTools: "Outils populaires",
    menu: "Menu",
    openMenu: "Ouvrir le menu",
    convertFromPdf: "Convertir depuis PDF",
    convertToPdf: "Convertir en PDF",
    editPdf: "Modifier PDF",
    utilityTools: "Outils utilitaires",
    compressPdf: "Compresser PDF",
    freeToolsCount: "43+ outils PDF gratuits",
    heroBadge: "43+ outils PDF gratuits - Sans inscription",
    heroTitle: "Outils PDF professionnels",
    heroFree: "100% Gratuit en ligne",
    heroSubtitle: "Convertissez, fusionnez, compressez et modifiez des fichiers PDF instantanément. Approuvé par des millions d'utilisateurs dans le monde.",
    heroDropFile: "Déposez votre fichier ici ou cliquez pour télécharger",
    heroChooseTool: "Puis choisissez ce que vous voulez faire avec",
    splitPdf: "Diviser PDF",
    whatWouldYouLikeToDo: "Que souhaitez-vous faire ?",
    viewAllTools: "Voir tous les 43+ outils",
    featuredTools: "Outils en vedette",
    mostPopular: "Le plus populaire",
    allPdfTools: "Tous les outils PDF",
    completeToolkit: "Kit complet",
    allPdfToolsSubtitle: "Choisissez parmi 43+ outils professionnels pour tous vos besoins PDF",
    simpleProcess: "Processus simple",
    howItWorks: "Comment ça marche",
    howItWorksSubtitle: "Trois étapes simples pour transformer vos fichiers PDF",
    step1Title: "Choisissez votre outil",
    step2Title: "Téléchargez votre fichier",
    step3Title: "Téléchargez le résultat",
    whyChooseUs: "Pourquoi nous choisir",
    whyPdfHub24: "Pourquoi PDF HUB 24 ?",
    whyChooseSubtitle: "Approuvé par des utilisateurs du monde entier pour un traitement PDF rapide, sécurisé et fiable",
    viewAllArticles: "Voir tous les articles",
    featuredLabel: "En vedette",
    useTool: "Utiliser",
        gdprCompliant: "Conforme au RGPD",
    noRegistration: "Sans inscription",
    showAllTools: "Afficher tous les {n} outils",
    showFewerTools: "Afficher moins d'outils",
  },
  pt: {
    home: "Início",
    allTools: "Todas as ferramentas",
    blog: "Blog",
    pdfToWord: "PDF para Word",
    merge: "Unir PDF",
    compress: "Comprimir",
    languageSwitcher: "Idioma",
    bannerText: "Esta página está disponível em",
    bannerSwitch: "Mudar para",
    bannerDismiss: "Fechar",
    uploadYourFiles: "Envie seus arquivos",
    dropFilesHere: "Solte seus arquivos aqui!",
    releaseToUpload: "Solte para enviar",
    tapToSelectFile: "Toque para selecionar seu arquivo",
    tapToSelectFiles: "Toque para selecionar até {n} arquivos",
    selectFile: "Selecionar arquivo",
    selectFiles: "Selecionar arquivos",
    selectedFile: "Arquivo selecionado",
    selectedFiles: "Arquivos selecionados ({n}/{max})",
    addMore: "Adicionar mais",
    clearAll: "Limpar tudo",
    secure: "Seguro",
    fast: "Rápido",
    free: "Grátis",
    hundredFree: "100% Grátis",
    noLimits: "Sem limites",
    noHiddenCosts: "Sem custos ocultos",
    sslEncrypted: "Criptografia SSL",
    cloudPowered: "Cloud potente",
    unlimitedUse: "Uso ilimitado",
    popularTools: "Ferramentas populares",
    menu: "Menu",
    openMenu: "Abrir menu",
    convertFromPdf: "Converter de PDF",
    convertToPdf: "Converter para PDF",
    editPdf: "Editar PDF",
    utilityTools: "Ferramentas utilitárias",
    compressPdf: "Comprimir PDF",
    freeToolsCount: "43+ ferramentas PDF grátis",
    heroBadge: "43+ ferramentas PDF grátis - Sem cadastro",
    heroTitle: "Ferramentas PDF profissionais",
    heroFree: "100% Grátis Online",
    heroSubtitle: "Converta, una, comprima e edite arquivos PDF instantaneamente. Confiado por milhões de usuários em todo o mundo.",
    heroDropFile: "Solte seu arquivo aqui ou clique para enviar",
    heroChooseTool: "Depois escolha o que deseja fazer com ele",
    splitPdf: "Dividir PDF",
    whatWouldYouLikeToDo: "O que você gostaria de fazer?",
    viewAllTools: "Ver todas as 43+ ferramentas",
    featuredTools: "Ferramentas em destaque",
    mostPopular: "Mais populares",
    allPdfTools: "Todas as ferramentas PDF",
    completeToolkit: "Kit completo",
    allPdfToolsSubtitle: "Escolha entre 43+ ferramentas profissionais para todas as suas necessidades de PDF",
    simpleProcess: "Processo simples",
    howItWorks: "Como funciona",
    howItWorksSubtitle: "Três etapas simples para transformar seus arquivos PDF",
    step1Title: "Escolha sua ferramenta",
    step2Title: "Faça upload do seu arquivo",
    step3Title: "Baixe o resultado",
    whyChooseUs: "Por que nos escolher",
    whyPdfHub24: "Por que PDF HUB 24?",
    whyChooseSubtitle: "Confiado por usuários em todo o mundo para processamento de PDF rápido, seguro e confiável",
    viewAllArticles: "Ver todos os artigos",
    featuredLabel: "Em destaque",
    useTool: "Usar",
        gdprCompliant: "Conforme com GDPR",
    noRegistration: "Sem registro",
    showAllTools: "Mostrar todas as {n} ferramentas",
    showFewerTools: "Mostrar menos ferramentas",
  },
};

export function t(lang: string, key: string): string {
  return UI_TRANSLATIONS[lang]?.[key] || UI_TRANSLATIONS["en"][key] || key;
}

export function tFormat(lang: string, key: string, vars: Record<string, string | number>): string {
  let str = t(lang, key);
  for (const [k, v] of Object.entries(vars)) {
    str = str.replace(`{${k}}`, String(v));
  }
  return str;
}

export const TOOL_TITLE_TRANSLATIONS: Record<string, Partial<Record<string, string>>> = {
  "merge":          { es: "Unir PDF",            ar: "دمج PDF",              hi: "PDF जोड़ें",           fr: "Fusionner PDF",       pt: "Unir PDF" },
  "split":          { es: "Dividir PDF",          ar: "تقسيم PDF",            hi: "PDF विभाजित करें",    fr: "Diviser PDF",         pt: "Dividir PDF" },
  "compress":       { es: "Comprimir PDF",        ar: "ضغط PDF",              hi: "PDF कम्प्रेस",         fr: "Compresser PDF",      pt: "Comprimir PDF" },
  "pdf-to-word":    { es: "PDF a Word",           ar: "PDF إلى Word",         hi: "PDF से Word",         fr: "PDF en Word",         pt: "PDF para Word" },
  "pdf-to-jpg":     { es: "PDF a JPG",            ar: "PDF إلى JPG",          hi: "PDF से JPG",          fr: "PDF en JPG",          pt: "PDF para JPG" },
  "pdf-to-png":     { es: "PDF a PNG",            ar: "PDF إلى PNG",          hi: "PDF से PNG",          fr: "PDF en PNG",          pt: "PDF para PNG" },
  "pdf-to-excel":   { es: "PDF a Excel",          ar: "PDF إلى إكسيل",        hi: "PDF से Excel",        fr: "PDF en Excel",        pt: "PDF para Excel" },
  "pdf-to-ppt":     { es: "PDF a PowerPoint",     ar: "PDF إلى PowerPoint",   hi: "PDF से PowerPoint",   fr: "PDF en PowerPoint",   pt: "PDF para PowerPoint" },
  "jpg-to-pdf":     { es: "JPG a PDF",            ar: "JPG إلى PDF",          hi: "JPG से PDF",          fr: "JPG en PDF",          pt: "JPG para PDF" },
  "png-to-pdf":     { es: "PNG a PDF",            ar: "PNG إلى PDF",          hi: "PNG से PDF",          fr: "PNG en PDF",          pt: "PNG para PDF" },
  "word-to-pdf":    { es: "Word a PDF",           ar: "وورد إلى PDF",         hi: "Word से PDF",         fr: "Word en PDF",         pt: "Word para PDF" },
  "excel-to-pdf":   { es: "Excel a PDF",          ar: "إكسيل إلى PDF",        hi: "Excel से PDF",        fr: "Excel en PDF",        pt: "Excel para PDF" },
  "ppt-to-pdf":     { es: "PowerPoint a PDF",     ar: "PowerPoint إلى PDF",   hi: "PowerPoint से PDF",   fr: "PowerPoint en PDF",   pt: "PowerPoint para PDF" },
  "protect":        { es: "Proteger PDF",         ar: "حماية PDF",            hi: "PDF सुरक्षित करें",    fr: "Protéger PDF",        pt: "Proteger PDF" },
  "unlock":         { es: "Desbloquear PDF",      ar: "فتح قفل PDF",           hi: "PDF अनलॉक करें",      fr: "Déverrouiller PDF",   pt: "Desbloquear PDF" },
  "sign":           { es: "Firmar PDF",           ar: "توقيع PDF",            hi: "PDF साइन करें",        fr: "Signer PDF",          pt: "Assinar PDF" },
  "rotate":         { es: "Rotar PDF",            ar: "تدوير PDF",            hi: "PDF घुमाएं",          fr: "Pivoter PDF",         pt: "Rotacionar PDF" },
  "watermark":      { es: "Marca de agua PDF",    ar: "علامة مائية PDF",      hi: "PDF वॉटरमार्क",       fr: "Filigrane PDF",       pt: "Marca d'água PDF" },
  "grayscale":      { es: "PDF en escala de grises", ar: "PDF رمادي",         hi: "PDF ग्रेस्केल",        fr: "PDF en niveaux de gris", pt: "PDF em tons de cinza" },
  "ocr-pdf":        { es: "OCR PDF",              ar: "OCR PDF",              hi: "OCR PDF",              fr: "OCR PDF",             pt: "OCR PDF" },
  "image-compressor": { es: "Comprimir imágenes", ar: "ضغط الصور",            hi: "इमेज कम्प्रेस",        fr: "Compresser images",   pt: "Comprimir imagens" },
  "image-resize":   { es: "Redimensionar imagen", ar: "تغيير حجم الصورة",    hi: "इमेज रीसाइज़",         fr: "Redimensionner image",pt: "Redimensionar imagem" },
  "image-crop":     { es: "Recortar imagen",      ar: "قص الصورة",            hi: "इमेज क्रॉप",          fr: "Rogner image",        pt: "Recortar imagem" },
  "image-convert":  { es: "Convertir imagen",     ar: "تحويل الصورة",         hi: "इमेज कन्वर्ट",         fr: "Convertir image",     pt: "Converter imagem" },
  "edit-pdf":       { es: "Editar PDF",           ar: "تعديل PDF",            hi: "PDF संपादित करें",     fr: "Modifier PDF",        pt: "Editar PDF" },
  "annotate":       { es: "Anotar PDF",           ar: "تعليق على PDF",        hi: "PDF एनोटेट",          fr: "Annoter PDF",         pt: "Anotar PDF" },
  "redact":         { es: "Redactar PDF",         ar: "تحرير PDF",            hi: "PDF रेडेक्ट",          fr: "Biffer PDF",          pt: "Redigir PDF" },
  "add-page-numbers": { es: "Añadir números de página", ar: "إضافة أرقام الصفحات", hi: "पेज नंबर जोड़ें",   fr: "Ajouter numéros de page", pt: "Adicionar números de página" },
  "remove-pages":   { es: "Eliminar páginas",     ar: "حذف صفحات",            hi: "पेज हटाएं",            fr: "Supprimer pages",     pt: "Remover páginas" },
  "extract-pages":  { es: "Extraer páginas",      ar: "استخراج صفحات",        hi: "पेज निकालें",          fr: "Extraire pages",      pt: "Extrair páginas" },
  "reorder-pages":  { es: "Reordenar páginas",    ar: "إعادة ترتيب الصفحات",  hi: "पेज क्रम बदलें",      fr: "Réorganiser pages",   pt: "Reordenar páginas" },
};

export function getToolTitle(toolId: string, lang: string, fallback: string): string {
  if (lang === "en") return fallback;
  return TOOL_TITLE_TRANSLATIONS[toolId]?.[lang] || fallback;
}
