export interface Language {
  code: string;
  hreflang: string;
  label: string;
  nativeLabel: string;
  dir: "ltr" | "rtl";
  flag: string;
}

export const SUPPORTED_LANGUAGES: Language[] = [
  { code: "en", hreflang: "en", label: "English", nativeLabel: "English", dir: "ltr", flag: "🇺🇸" },
  { code: "es", hreflang: "es", label: "Spanish", nativeLabel: "Español", dir: "ltr", flag: "🇪🇸" },
  { code: "ar", hreflang: "ar", label: "Arabic", nativeLabel: "العربية", dir: "rtl", flag: "🇸🇦" },
  { code: "hi", hreflang: "hi", label: "Hindi", nativeLabel: "हिंदी", dir: "ltr", flag: "🇮🇳" },
  { code: "fr", hreflang: "fr", label: "French", nativeLabel: "Français", dir: "ltr", flag: "🇫🇷" },
  { code: "pt", hreflang: "pt", label: "Portuguese", nativeLabel: "Português", dir: "ltr", flag: "🇧🇷" },
  { code: "de", hreflang: "de", label: "German", nativeLabel: "Deutsch", dir: "ltr", flag: "🇩🇪" },
  { code: "zh", hreflang: "zh", label: "Chinese", nativeLabel: "中文", dir: "ltr", flag: "🇨🇳" },
  { code: "ja", hreflang: "ja", label: "Japanese", nativeLabel: "日本語", dir: "ltr", flag: "🇯🇵" },
  { code: "id", hreflang: "id", label: "Indonesian", nativeLabel: "Bahasa Indonesia", dir: "ltr", flag: "🇮🇩" },
  { code: "ru", hreflang: "ru", label: "Russian", nativeLabel: "Русский", dir: "ltr", flag: "🇷🇺" },
  { code: "it", hreflang: "it", label: "Italian", nativeLabel: "Italiano", dir: "ltr", flag: "🇮🇹" },
  { code: "ur", hreflang: "ur", label: "Urdu", nativeLabel: "اردو", dir: "rtl", flag: "🇵🇰" },
];

export const LANG_CODES = SUPPORTED_LANGUAGES.map(l => l.code);
export const NON_DEFAULT_LANG_CODES = LANG_CODES.filter(c => c !== "en");

export function getLang(code: string): Language {
  return SUPPORTED_LANGUAGES.find(l => l.code === code) || SUPPORTED_LANGUAGES[0];
}

export function detectBrowserLang(): string {
  const nav = typeof navigator !== "undefined" ? navigator : null;
  if (!nav) return "en";
  const preferred = (nav.language || "en").split("-")[0].toLowerCase();
  return NON_DEFAULT_LANG_CODES.includes(preferred) ? preferred : "en";
}

export function getLangFromPath(pathname: string): { lang: string; basePath: string } {
  const match = pathname.match(/^\/(es|ar|hi|fr|pt|de|zh|ja|id|ru|it|ur)(\/.*)?$/);
  if (match) {
    return { lang: match[1], basePath: match[2] || "/" };
  }
  return { lang: "en", basePath: pathname };
}

export function buildLangPath(lang: string, basePath: string): string {
  if (lang === "en") return basePath;
  const normalizedBase = basePath.startsWith("/") ? basePath : `/${basePath}`;
  return `/${lang}${normalizedBase === "/" ? "" : normalizedBase}`;
}

export const UI_TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    home: "Home",
    allTools: "All Tools",
    blog: "Blog",
    pdfToWord: "PDF to Word",
    merge: "Merge PDF",
    compress: "Compress",
    languageSwitcher: "Language",
    bannerText: "This page is available in",
    bannerSwitch: "Switch to",
    bannerDismiss: "Dismiss",
    uploadYourFiles: "Upload Your Files",
    dropFilesHere: "Drop your files here!",
    releaseToUpload: "Release to upload",
    tapToSelectFile: "Tap to select your file",
    tapToSelectFiles: "Tap to select up to {n} files",
    selectFile: "Select File",
    selectFiles: "Select Files",
    selectedFile: "Selected File",
    selectedFiles: "Selected Files ({n}/{max})",
    addMore: "Add More",
    clearAll: "Clear All",
    secure: "Secure",
    fast: "Fast",
    free: "Free",
    hundredFree: "100% Free",
    noLimits: "No Limits",
    noHiddenCosts: "No hidden costs",
    sslEncrypted: "SSL encrypted",
    cloudPowered: "Cloud powered",
    unlimitedUse: "Unlimited use",
    popularTools: "Popular Tools",
    menu: "Menu",
    openMenu: "Open menu",
    convertFromPdf: "Convert from PDF",
    convertToPdf: "Convert to PDF",
    editPdf: "Edit PDF",
    utilityTools: "Utility Tools",
    compressPdf: "Compress PDF",
    freeToolsCount: "43+ Free PDF Tools",
    heroBadge: "43+ Free PDF Tools - No Registration Required",
    heroTitle: "Professional PDF Tools",
    heroFree: "100% Free Online",
    heroSubtitle: "Convert, merge, compress, and edit PDF files instantly. Trusted by millions of users worldwide.",
    heroDropFile: "Drop your file here or click to upload",
    heroChooseTool: "Then choose what you want to do with it",
    splitPdf: "Split PDF",
    whatWouldYouLikeToDo: "What would you like to do?",
    viewAllTools: "View All 43+ Tools",
    featuredTools: "Featured Tools",
    mostPopular: "Most Popular",
    allPdfTools: "All PDF Tools",
    completeToolkit: "Complete Toolkit",
    allPdfToolsSubtitle: "Choose from 43+ professional tools for all your PDF needs",
    simpleProcess: "Simple Process",
    howItWorks: "How It Works",
    howItWorksSubtitle: "Three simple steps to transform your PDF files",
    step1Title: "Choose Your Tool",
    step2Title: "Upload Your File",
    step3Title: "Download Result",
    whyChooseUs: "Why Choose Us",
    whyPdfHub24: "Why PDF HUB 24?",
    whyChooseSubtitle: "Trusted by users worldwide for fast, secure, and reliable PDF processing",
    viewAllArticles: "View All Articles",
    featuredLabel: "Featured",
    useTool: "Use",
        gdprCompliant: "GDPR Compliant",
    noRegistration: "No Registration",
    showAllTools: "Show all {n} tools",
    showFewerTools: "Show fewer tools",
    backToTools: "Back to Tools",
    euPrivacyLaw: "EU Privacy Law",
    noAccountNeeded: "No account needed",
    uploadStep: "Upload",
    configureStep: "Configure",
    downloadStep: "Download",
    processingFile: "Processing your file...",
    successTitle: "Done!",
    downloadBtn: "Download",
    processAnotherBtn: "Process Another File",
    compressionLevelTitle: "Choose Compression Level",
    compressionLevelDesc: "Select the level that best fits your needs",
    lowCompression: "Low Compression",
    mediumCompression: "Medium Compression",
    highCompression: "High Compression",
    recommended: "Recommended",
    qualityBadge: "Quality",
    smallestBadge: "Smallest",
    lowCompressionDesc: "Best quality, slightly smaller file size",
    mediumCompressionDesc: "Balanced quality and file size",
    highCompressionDesc: "Smallest file size, reduced image quality",
    compressPdfBtn: "Compress PDF",
    compressCompleteTitle: "Compression Complete!",
    compressReadyDesc: "Your PDF has been optimized and is ready for download",
    originalSizeLabel: "Original",
    savedLabel: "Saved",
    newSizeLabel: "New Size",
    downloadCompressedBtn: "Download Compressed PDF",
    compressAnotherBtn: "Compress Another File",
    mergePdfsBtn: "Merge PDFs",
    splitPdfBtn: "Split PDF",
    batchCompressTip: "Need to compress multiple PDFs at once?",
    tryBatchCompress: "Try Batch Compress",
    processingYourFile: "Processing Your File",
    processingFiles: "Processing {n} Files",
    processedSecurely: "Your file is being processed securely",
    fileReadyDownload: "Your file is ready for download",
    errorTitle: "Something Went Wrong",
    errorMessage: "An error occurred while processing your file. Please try again.",
    tryAgain: "Try Again",
  },
  es: {
    home: "Inicio",
    allTools: "Todas las herramientas",
    blog: "Blog",
    pdfToWord: "PDF a Word",
    merge: "Unir PDF",
    compress: "Comprimir",
    languageSwitcher: "Idioma",
    bannerText: "Esta página está disponible en",
    bannerSwitch: "Cambiar a",
    bannerDismiss: "Cerrar",
    uploadYourFiles: "Sube tus archivos",
    dropFilesHere: "¡Suelta tus archivos aquí!",
    releaseToUpload: "Suelta para subir",
    tapToSelectFile: "Toca para seleccionar tu archivo",
    tapToSelectFiles: "Toca para seleccionar hasta {n} archivos",
    selectFile: "Seleccionar archivo",
    selectFiles: "Seleccionar archivos",
    selectedFile: "Archivo seleccionado",
    selectedFiles: "Archivos seleccionados ({n}/{max})",
    addMore: "Añadir más",
    clearAll: "Limpiar todo",
    secure: "Seguro",
    fast: "Rápido",
    free: "Gratis",
    hundredFree: "100% Gratis",
    noLimits: "Sin límites",
    noHiddenCosts: "Sin costos ocultos",
    sslEncrypted: "Cifrado SSL",
    cloudPowered: "Nube potente",
    unlimitedUse: "Uso ilimitado",
    popularTools: "Herramientas populares",
    menu: "Menú",
    openMenu: "Abrir menú",
    convertFromPdf: "Convertir desde PDF",
    convertToPdf: "Convertir a PDF",
    editPdf: "Editar PDF",
    utilityTools: "Herramientas de utilidad",
    compressPdf: "Comprimir PDF",
    freeToolsCount: "43+ herramientas PDF gratis",
    heroBadge: "43+ herramientas PDF gratuitas - Sin registro",
    heroTitle: "Herramientas PDF profesionales",
    heroFree: "100% Gratis Online",
    heroSubtitle: "Convierte, une, comprime y edita archivos PDF al instante. Confiado por millones de usuarios en todo el mundo.",
    heroDropFile: "Suelta tu archivo aquí o haz clic para subir",
    heroChooseTool: "Luego elige qué quieres hacer con él",
    splitPdf: "Dividir PDF",
    whatWouldYouLikeToDo: "¿Qué te gustaría hacer?",
    viewAllTools: "Ver todas las 43+ herramientas",
    featuredTools: "Herramientas destacadas",
    mostPopular: "Más populares",
    allPdfTools: "Todas las herramientas PDF",
    completeToolkit: "Kit completo",
    allPdfToolsSubtitle: "Elige entre 43+ herramientas profesionales para todas tus necesidades PDF",
    simpleProcess: "Proceso sencillo",
    howItWorks: "Cómo funciona",
    howItWorksSubtitle: "Tres sencillos pasos para transformar tus archivos PDF",
    step1Title: "Elige tu herramienta",
    step2Title: "Sube tu archivo",
    step3Title: "Descarga el resultado",
    whyChooseUs: "¿Por qué elegirnos?",
    whyPdfHub24: "¿Por qué PDF HUB 24?",
    whyChooseSubtitle: "Confiado por usuarios en todo el mundo para un procesamiento de PDF rápido, seguro y confiable",
    viewAllArticles: "Ver todos los artículos",
    featuredLabel: "Destacado",
    useTool: "Usar",
        gdprCompliant: "Cumple con GDPR",
    noRegistration: "Sin registro",
    showAllTools: "Mostrar todas las {n} herramientas",
    showFewerTools: "Mostrar menos herramientas",
    backToTools: "Volver a herramientas",
    euPrivacyLaw: "Ley de privacidad de la UE",
    noAccountNeeded: "Sin cuenta necesaria",
    uploadStep: "Subir",
    configureStep: "Configurar",
    downloadStep: "Descargar",
    processingFile: "Procesando tu archivo...",
    successTitle: "¡Listo!",
    downloadBtn: "Descargar",
    processAnotherBtn: "Procesar otro archivo",
    compressionLevelTitle: "Elige el nivel de compresión",
    compressionLevelDesc: "Selecciona el nivel que mejor se adapte a tus necesidades",
    lowCompression: "Compresión baja",
    mediumCompression: "Compresión media",
    highCompression: "Compresión alta",
    recommended: "Recomendado",
    qualityBadge: "Calidad",
    smallestBadge: "Mínimo",
    lowCompressionDesc: "Mejor calidad, tamaño de archivo ligeramente menor",
    mediumCompressionDesc: "Calidad y tamaño de archivo equilibrados",
    highCompressionDesc: "Tamaño mínimo, calidad de imagen reducida",
    compressPdfBtn: "Comprimir PDF",
    compressCompleteTitle: "¡Compresión completada!",
    compressReadyDesc: "Tu PDF ha sido optimizado y está listo para descargar",
    originalSizeLabel: "Original",
    savedLabel: "Ahorrado",
    newSizeLabel: "Nuevo tamaño",
    downloadCompressedBtn: "Descargar PDF comprimido",
    compressAnotherBtn: "Comprimir otro archivo",
    mergePdfsBtn: "Unir PDFs",
    splitPdfBtn: "Dividir PDF",
    batchCompressTip: "¿Necesitas comprimir varios PDFs a la vez?",
    tryBatchCompress: "Probar compresión por lotes",
    processingYourFile: "Procesando tu archivo",
    processingFiles: "Procesando {n} archivos",
    processedSecurely: "Tu archivo se procesa de forma segura",
    fileReadyDownload: "Tu archivo está listo para descargar",
    errorTitle: "Algo salió mal",
    errorMessage: "Ocurrió un error al procesar tu archivo. Por favor, inténtalo de nuevo.",
    tryAgain: "Intentar de nuevo",
  },
  ar: {
    home: "الرئيسية",
    allTools: "جميع الأدوات",
    blog: "المدونة",
    pdfToWord: "PDF إلى Word",
    merge: "دمج PDF",
    compress: "ضغط",
    languageSwitcher: "اللغة",
    bannerText: "هذه الصفحة متاحة باللغة",
    bannerSwitch: "التبديل إلى",
    bannerDismiss: "إغلاق",
    uploadYourFiles: "قم برفع ملفاتك",
    dropFilesHere: "أسقط ملفاتك هنا!",
    releaseToUpload: "أطلق للرفع",
    tapToSelectFile: "انقر لاختيار ملفك",
    tapToSelectFiles: "انقر لاختيار حتى {n} ملفات",
    selectFile: "اختر ملفاً",
    selectFiles: "اختر ملفات",
    selectedFile: "الملف المختار",
    selectedFiles: "الملفات المختارة ({n}/{max})",
    addMore: "أضف المزيد",
    clearAll: "مسح الكل",
    secure: "آمن",
    fast: "سريع",
    free: "مجاني",
    hundredFree: "100% مجاني",
    noLimits: "بلا حدود",
    noHiddenCosts: "لا تكاليف خفية",
    sslEncrypted: "مشفر بـ SSL",
    cloudPowered: "مدعوم بالسحابة",
    unlimitedUse: "استخدام غير محدود",
    popularTools: "الأدوات الشائعة",
    menu: "القائمة",
    openMenu: "فتح القائمة",
    convertFromPdf: "التحويل من PDF",
    convertToPdf: "التحويل إلى PDF",
    editPdf: "تعديل PDF",
    utilityTools: "أدوات المرافق",
    compressPdf: "ضغط PDF",
    freeToolsCount: "أكثر من 43 أداة PDF مجانية",
    heroBadge: "أكثر من 43 أداة PDF مجانية - بدون تسجيل",
    heroTitle: "أدوات PDF احترافية",
    heroFree: "100% مجاني عبر الإنترنت",
    heroSubtitle: "حوّل ملفات PDF ودمجها واضغطها وعدّلها على الفور. موثوق به من قبل ملايين المستخدمين حول العالم.",
    heroDropFile: "أسقط ملفك هنا أو انقر للرفع",
    heroChooseTool: "ثم اختر ما تريد فعله به",
    splitPdf: "تقسيم PDF",
    whatWouldYouLikeToDo: "ماذا تريد أن تفعل؟",
    viewAllTools: "عرض جميع الأدوات 43+",
    featuredTools: "الأدوات المميزة",
    mostPopular: "الأكثر شعبية",
    allPdfTools: "جميع أدوات PDF",
    completeToolkit: "مجموعة أدوات كاملة",
    allPdfToolsSubtitle: "اختر من بين 43+ أداة احترافية لجميع احتياجاتك من PDF",
    simpleProcess: "عملية بسيطة",
    howItWorks: "كيف يعمل",
    howItWorksSubtitle: "ثلاث خطوات بسيطة لتحويل ملفات PDF الخاصة بك",
    step1Title: "اختر أداتك",
    step2Title: "ارفع ملفك",
    step3Title: "تنزيل النتيجة",
    whyChooseUs: "لماذا تختارنا",
    whyPdfHub24: "لماذا PDF HUB 24؟",
    whyChooseSubtitle: "موثوق به من قبل المستخدمين في جميع أنحاء العالم لمعالجة PDF السريعة والآمنة والموثوقة",
    viewAllArticles: "عرض جميع المقالات",
    featuredLabel: "مميز",
    useTool: "استخدم",
        gdprCompliant: "متوافق مع GDPR",
    noRegistration: "بدون تسجيل",
    showAllTools: "عرض جميع الأدوات {n}",
    showFewerTools: "عرض أدوات أقل",
    backToTools: "العودة إلى الأدوات",
    euPrivacyLaw: "قانون الخصوصية الأوروبي",
    noAccountNeeded: "لا حاجة لحساب",
    uploadStep: "رفع",
    configureStep: "إعداد",
    downloadStep: "تنزيل",
    processingFile: "جاري معالجة ملفك...",
    successTitle: "تم!",
    downloadBtn: "تنزيل",
    processAnotherBtn: "معالجة ملف آخر",
    compressionLevelTitle: "اختر مستوى الضغط",
    compressionLevelDesc: "حدد المستوى الأنسب لاحتياجاتك",
    lowCompression: "ضغط منخفض",
    mediumCompression: "ضغط متوسط",
    highCompression: "ضغط عالٍ",
    recommended: "موصى به",
    qualityBadge: "جودة",
    smallestBadge: "الأصغر",
    lowCompressionDesc: "أفضل جودة، حجم ملف أصغر قليلاً",
    mediumCompressionDesc: "توازن بين الجودة وحجم الملف",
    highCompressionDesc: "أصغر حجم، جودة صورة مخفضة",
    compressPdfBtn: "ضغط PDF",
    compressCompleteTitle: "اكتمل الضغط!",
    compressReadyDesc: "تم تحسين ملف PDF الخاص بك وهو جاهز للتنزيل",
    originalSizeLabel: "الأصلي",
    savedLabel: "المحفوظ",
    newSizeLabel: "الحجم الجديد",
    downloadCompressedBtn: "تنزيل PDF المضغوط",
    compressAnotherBtn: "ضغط ملف آخر",
    mergePdfsBtn: "دمج PDF",
    splitPdfBtn: "تقسيم PDF",
    batchCompressTip: "هل تحتاج إلى ضغط عدة ملفات PDF مرة واحدة؟",
    tryBatchCompress: "جرب الضغط الدفعي",
    processingYourFile: "جاري معالجة ملفك",
    processingFiles: "جاري معالجة {n} ملفات",
    processedSecurely: "يتم معالجة ملفك بشكل آمن",
    fileReadyDownload: "ملفك جاهز للتنزيل",
    errorTitle: "حدث خطأ ما",
    errorMessage: "حدث خطأ أثناء معالجة ملفك. يرجى المحاولة مجدداً.",
    tryAgain: "حاول مرة أخرى",
  },
  hi: {
    home: "होम",
    allTools: "सभी टूल्स",
    blog: "ब्लॉग",
    pdfToWord: "PDF से Word",
    merge: "PDF जोड़ें",
    compress: "कम्प्रेस",
    languageSwitcher: "भाषा",
    bannerText: "यह पृष्ठ उपलब्ध है",
    bannerSwitch: "स्विच करें",
    bannerDismiss: "बंद करें",
    uploadYourFiles: "अपनी फ़ाइलें अपलोड करें",
    dropFilesHere: "यहाँ फ़ाइलें छोड़ें!",
    releaseToUpload: "अपलोड करने के लिए छोड़ें",
    tapToSelectFile: "फ़ाइल चुनने के लिए टैप करें",
    tapToSelectFiles: "{n} फ़ाइलें चुनने के लिए टैप करें",
    selectFile: "फ़ाइल चुनें",
    selectFiles: "फ़ाइलें चुनें",
    selectedFile: "चुनी गई फ़ाइल",
    selectedFiles: "चुनी गई फ़ाइलें ({n}/{max})",
    addMore: "और जोड़ें",
    clearAll: "सब हटाएं",
    secure: "सुरक्षित",
    fast: "तेज़",
    free: "मुफ़्त",
    hundredFree: "100% मुफ़्त",
    noLimits: "कोई सीमा नहीं",
    noHiddenCosts: "कोई छुपी लागत नहीं",
    sslEncrypted: "SSL एन्क्रिप्टेड",
    cloudPowered: "क्लाउड पावर्ड",
    unlimitedUse: "असीमित उपयोग",
    popularTools: "लोकप्रिय टूल्स",
    menu: "मेनू",
    openMenu: "मेनू खोलें",
    convertFromPdf: "PDF से कन्वर्ट करें",
    convertToPdf: "PDF में कन्वर्ट करें",
    editPdf: "PDF संपादित करें",
    utilityTools: "उपयोगिता टूल्स",
    compressPdf: "PDF कम्प्रेस",
    freeToolsCount: "43+ मुफ़्त PDF टूल्स",
    heroBadge: "43+ मुफ़्त PDF टूल्स - कोई पंजीकरण नहीं",
    heroTitle: "प्रोफेशनल PDF टूल्स",
    heroFree: "100% मुफ़्त ऑनलाइन",
    heroSubtitle: "PDF फ़ाइलें तुरंत कन्वर्ट, मर्ज, कम्प्रेस और एडिट करें। दुनिया भर के लाखों उपयोगकर्ताओं द्वारा विश्वसनीय।",
    heroDropFile: "यहाँ फ़ाइल छोड़ें या अपलोड करने के लिए क्लिक करें",
    heroChooseTool: "फिर चुनें कि आप इसके साथ क्या करना चाहते हैं",
    splitPdf: "PDF विभाजित करें",
    whatWouldYouLikeToDo: "आप क्या करना चाहते हैं?",
    viewAllTools: "सभी 43+ टूल्स देखें",
    featuredTools: "विशेष टूल्स",
    mostPopular: "सबसे लोकप्रिय",
    allPdfTools: "सभी PDF टूल्स",
    completeToolkit: "पूर्ण टूलकिट",
    allPdfToolsSubtitle: "आपकी सभी PDF जरूरतों के लिए 43+ प्रोफेशनल टूल्स में से चुनें",
    simpleProcess: "सरल प्रक्रिया",
    howItWorks: "यह कैसे काम करता है",
    howItWorksSubtitle: "आपकी PDF फ़ाइलों को बदलने के लिए तीन सरल चरण",
    step1Title: "अपना टूल चुनें",
    step2Title: "अपनी फ़ाइल अपलोड करें",
    step3Title: "परिणाम डाउनलोड करें",
    whyChooseUs: "हमें क्यों चुनें",
    whyPdfHub24: "PDF HUB 24 क्यों?",
    whyChooseSubtitle: "तेज़, सुरक्षित और विश्वसनीय PDF प्रोसेसिंग के लिए दुनिया भर के उपयोगकर्ताओं द्वारा विश्वसनीय",
    viewAllArticles: "सभी लेख देखें",
    featuredLabel: "विशेष",
    useTool: "उपयोग करें",
        gdprCompliant: "GDPR अनुपालित",
    noRegistration: "कोई पंजीकरण नहीं",
    showAllTools: "सभी {n} टूल्स दिखाएं",
    showFewerTools: "कम टूल्स दिखाएं",
    backToTools: "टूल्स पर वापस जाएं",
    euPrivacyLaw: "EU गोपनीयता कानून",
    noAccountNeeded: "खाते की जरूरत नहीं",
    uploadStep: "अपलोड",
    configureStep: "सेटिंग",
    downloadStep: "डाउनलोड",
    processingFile: "आपकी फ़ाइल प्रोसेस हो रही है...",
    successTitle: "हो गया!",
    downloadBtn: "डाउनलोड",
    processAnotherBtn: "दूसरी फ़ाइल प्रोसेस करें",
    compressionLevelTitle: "कंप्रेशन स्तर चुनें",
    compressionLevelDesc: "अपनी जरूरत के अनुसार स्तर चुनें",
    lowCompression: "कम कंप्रेशन",
    mediumCompression: "मध्यम कंप्रेशन",
    highCompression: "अधिक कंप्रेशन",
    recommended: "अनुशंसित",
    qualityBadge: "गुणवत्ता",
    smallestBadge: "सबसे छोटा",
    lowCompressionDesc: "सर्वोत्तम गुणवत्ता, फ़ाइल थोड़ी छोटी",
    mediumCompressionDesc: "गुणवत्ता और आकार में संतुलन",
    highCompressionDesc: "सबसे छोटा आकार, छवि गुणवत्ता कम",
    compressPdfBtn: "PDF कम्प्रेस करें",
    compressCompleteTitle: "कंप्रेशन पूर्ण!",
    compressReadyDesc: "आपकी PDF अनुकूलित हो गई है और डाउनलोड के लिए तैयार है",
    originalSizeLabel: "मूल",
    savedLabel: "बचाया",
    newSizeLabel: "नया आकार",
    downloadCompressedBtn: "कंप्रेस्ड PDF डाउनलोड करें",
    compressAnotherBtn: "दूसरी फ़ाइल कंप्रेस करें",
    mergePdfsBtn: "PDF जोड़ें",
    splitPdfBtn: "PDF विभाजित करें",
    batchCompressTip: "एक साथ कई PDF कम्प्रेस करने की जरूरत है?",
    tryBatchCompress: "बैच कंप्रेस आज़माएं",
    processingYourFile: "आपकी फ़ाइल प्रोसेस हो रही है",
    processingFiles: "{n} फ़ाइलें प्रोसेस हो रही हैं",
    processedSecurely: "आपकी फ़ाइल सुरक्षित तरीके से प्रोसेस हो रही है",
    fileReadyDownload: "आपकी फ़ाइल डाउनलोड के लिए तैयार है",
    errorTitle: "कुछ गलत हो गया",
    errorMessage: "आपकी फ़ाइल प्रोसेस करते समय त्रुटि हुई। कृपया पुनः प्रयास करें।",
    tryAgain: "फिर कोशिश करें",
  },
  fr: {
    home: "Accueil",
    allTools: "Tous les outils",
    blog: "Blog",
    pdfToWord: "PDF en Word",
    merge: "Fusionner PDF",
    compress: "Compresser",
    languageSwitcher: "Langue",
    bannerText: "Cette page est disponible en",
    bannerSwitch: "Passer à",
    bannerDismiss: "Fermer",
    uploadYourFiles: "Téléchargez vos fichiers",
    dropFilesHere: "Déposez vos fichiers ici !",
    releaseToUpload: "Relâchez pour télécharger",
    tapToSelectFile: "Touchez pour sélectionner votre fichier",
    tapToSelectFiles: "Touchez pour sélectionner jusqu'à {n} fichiers",
    selectFile: "Sélectionner un fichier",
    selectFiles: "Sélectionner des fichiers",
    selectedFile: "Fichier sélectionné",
    selectedFiles: "Fichiers sélectionnés ({n}/{max})",
    addMore: "Ajouter plus",
    clearAll: "Tout effacer",
    secure: "Sécurisé",
    fast: "Rapide",
    free: "Gratuit",
    hundredFree: "100% Gratuit",
    noLimits: "Sans limites",
    noHiddenCosts: "Aucun frais caché",
    sslEncrypted: "Chiffrement SSL",
    cloudPowered: "Cloud puissant",
    unlimitedUse: "Utilisation illimitée",
    popularTools: "Outils populaires",
    menu: "Menu",
    openMenu: "Ouvrir le menu",
    convertFromPdf: "Convertir depuis PDF",
    convertToPdf: "Convertir en PDF",
    editPdf: "Modifier PDF",
    utilityTools: "Outils utilitaires",
    compressPdf: "Compresser PDF",
    freeToolsCount: "43+ outils PDF gratuits",
    heroBadge: "43+ outils PDF gratuits - Sans inscription",
    heroTitle: "Outils PDF professionnels",
    heroFree: "100% Gratuit en ligne",
    heroSubtitle: "Convertissez, fusionnez, compressez et modifiez des fichiers PDF instantanément. Approuvé par des millions d'utilisateurs dans le monde.",
    heroDropFile: "Déposez votre fichier ici ou cliquez pour télécharger",
    heroChooseTool: "Puis choisissez ce que vous voulez faire avec",
    splitPdf: "Diviser PDF",
    whatWouldYouLikeToDo: "Que souhaitez-vous faire ?",
    viewAllTools: "Voir tous les 43+ outils",
    featuredTools: "Outils en vedette",
    mostPopular: "Le plus populaire",
    allPdfTools: "Tous les outils PDF",
    completeToolkit: "Kit complet",
    allPdfToolsSubtitle: "Choisissez parmi 43+ outils professionnels pour tous vos besoins PDF",
    simpleProcess: "Processus simple",
    howItWorks: "Comment ça marche",
    howItWorksSubtitle: "Trois étapes simples pour transformer vos fichiers PDF",
    step1Title: "Choisissez votre outil",
    step2Title: "Téléchargez votre fichier",
    step3Title: "Téléchargez le résultat",
    whyChooseUs: "Pourquoi nous choisir",
    whyPdfHub24: "Pourquoi PDF HUB 24 ?",
    whyChooseSubtitle: "Approuvé par des utilisateurs du monde entier pour un traitement PDF rapide, sécurisé et fiable",
    viewAllArticles: "Voir tous les articles",
    featuredLabel: "En vedette",
    useTool: "Utiliser",
        gdprCompliant: "Conforme au RGPD",
    noRegistration: "Sans inscription",
    showAllTools: "Afficher tous les {n} outils",
    showFewerTools: "Afficher moins d'outils",
    backToTools: "Retour aux outils",
    euPrivacyLaw: "Loi européenne sur la vie privée",
    noAccountNeeded: "Aucun compte nécessaire",
    uploadStep: "Télécharger",
    configureStep: "Configurer",
    downloadStep: "Télécharger",
    processingFile: "Traitement de votre fichier...",
    successTitle: "Terminé !",
    downloadBtn: "Télécharger",
    processAnotherBtn: "Traiter un autre fichier",
    compressionLevelTitle: "Choisir le niveau de compression",
    compressionLevelDesc: "Sélectionnez le niveau qui correspond à vos besoins",
    lowCompression: "Compression faible",
    mediumCompression: "Compression moyenne",
    highCompression: "Compression élevée",
    recommended: "Recommandé",
    qualityBadge: "Qualité",
    smallestBadge: "Minimal",
    lowCompressionDesc: "Meilleure qualité, taille de fichier légèrement réduite",
    mediumCompressionDesc: "Équilibre entre qualité et taille de fichier",
    highCompressionDesc: "Taille minimale, qualité d'image réduite",
    compressPdfBtn: "Compresser PDF",
    compressCompleteTitle: "Compression terminée !",
    compressReadyDesc: "Votre PDF a été optimisé et est prêt à être téléchargé",
    originalSizeLabel: "Original",
    savedLabel: "Économisé",
    newSizeLabel: "Nouvelle taille",
    downloadCompressedBtn: "Télécharger le PDF compressé",
    compressAnotherBtn: "Compresser un autre fichier",
    mergePdfsBtn: "Fusionner les PDFs",
    splitPdfBtn: "Diviser le PDF",
    batchCompressTip: "Besoin de compresser plusieurs PDFs à la fois ?",
    tryBatchCompress: "Essayer la compression par lot",
    processingYourFile: "Traitement de votre fichier",
    processingFiles: "Traitement de {n} fichiers",
    processedSecurely: "Votre fichier est traité en toute sécurité",
    fileReadyDownload: "Votre fichier est prêt à être téléchargé",
    errorTitle: "Quelque chose s'est mal passé",
    errorMessage: "Une erreur s'est produite lors du traitement de votre fichier. Veuillez réessayer.",
    tryAgain: "Réessayer",
  },
  pt: {
    home: "Início",
    allTools: "Todas as ferramentas",
    blog: "Blog",
    pdfToWord: "PDF para Word",
    merge: "Unir PDF",
    compress: "Comprimir",
    languageSwitcher: "Idioma",
    bannerText: "Esta página está disponível em",
    bannerSwitch: "Mudar para",
    bannerDismiss: "Fechar",
    uploadYourFiles: "Envie seus arquivos",
    dropFilesHere: "Solte seus arquivos aqui!",
    releaseToUpload: "Solte para enviar",
    tapToSelectFile: "Toque para selecionar seu arquivo",
    tapToSelectFiles: "Toque para selecionar até {n} arquivos",
    selectFile: "Selecionar arquivo",
    selectFiles: "Selecionar arquivos",
    selectedFile: "Arquivo selecionado",
    selectedFiles: "Arquivos selecionados ({n}/{max})",
    addMore: "Adicionar mais",
    clearAll: "Limpar tudo",
    secure: "Seguro",
    fast: "Rápido",
    free: "Grátis",
    hundredFree: "100% Grátis",
    noLimits: "Sem limites",
    noHiddenCosts: "Sem custos ocultos",
    sslEncrypted: "Criptografia SSL",
    cloudPowered: "Cloud potente",
    unlimitedUse: "Uso ilimitado",
    popularTools: "Ferramentas populares",
    menu: "Menu",
    openMenu: "Abrir menu",
    convertFromPdf: "Converter de PDF",
    convertToPdf: "Converter para PDF",
    editPdf: "Editar PDF",
    utilityTools: "Ferramentas utilitárias",
    compressPdf: "Comprimir PDF",
    freeToolsCount: "43+ ferramentas PDF grátis",
    heroBadge: "43+ ferramentas PDF grátis - Sem cadastro",
    heroTitle: "Ferramentas PDF profissionais",
    heroFree: "100% Grátis Online",
    heroSubtitle: "Converta, una, comprima e edite arquivos PDF instantaneamente. Confiado por milhões de usuários em todo o mundo.",
    heroDropFile: "Solte seu arquivo aqui ou clique para enviar",
    heroChooseTool: "Depois escolha o que deseja fazer com ele",
    splitPdf: "Dividir PDF",
    whatWouldYouLikeToDo: "O que você gostaria de fazer?",
    viewAllTools: "Ver todas as 43+ ferramentas",
    featuredTools: "Ferramentas em destaque",
    mostPopular: "Mais populares",
    allPdfTools: "Todas as ferramentas PDF",
    completeToolkit: "Kit completo",
    allPdfToolsSubtitle: "Escolha entre 43+ ferramentas profissionais para todas as suas necessidades de PDF",
    simpleProcess: "Processo simples",
    howItWorks: "Como funciona",
    howItWorksSubtitle: "Três etapas simples para transformar seus arquivos PDF",
    step1Title: "Escolha sua ferramenta",
    step2Title: "Faça upload do seu arquivo",
    step3Title: "Baixe o resultado",
    whyChooseUs: "Por que nos escolher",
    whyPdfHub24: "Por que PDF HUB 24?",
    whyChooseSubtitle: "Confiado por usuários em todo o mundo para processamento de PDF rápido, seguro e confiável",
    viewAllArticles: "Ver todos os artigos",
    featuredLabel: "Em destaque",
    useTool: "Usar",
        gdprCompliant: "Conforme com GDPR",
    noRegistration: "Sem registro",
    showAllTools: "Mostrar todas as {n} ferramentas",
    showFewerTools: "Mostrar menos ferramentas",
    backToTools: "Voltar às ferramentas",
    euPrivacyLaw: "Lei de Privacidade da UE",
    noAccountNeeded: "Sem conta necessária",
    uploadStep: "Enviar",
    configureStep: "Configurar",
    downloadStep: "Baixar",
    processingFile: "Processando seu arquivo...",
    successTitle: "Pronto!",
    downloadBtn: "Baixar",
    processAnotherBtn: "Processar outro arquivo",
    compressionLevelTitle: "Escolher nível de compressão",
    compressionLevelDesc: "Selecione o nível que melhor atende às suas necessidades",
    lowCompression: "Compressão baixa",
    mediumCompression: "Compressão média",
    highCompression: "Compressão alta",
    recommended: "Recomendado",
    qualityBadge: "Qualidade",
    smallestBadge: "Mínimo",
    lowCompressionDesc: "Melhor qualidade, tamanho de arquivo ligeiramente menor",
    mediumCompressionDesc: "Equilíbrio entre qualidade e tamanho do arquivo",
    highCompressionDesc: "Menor tamanho, qualidade de imagem reduzida",
    compressPdfBtn: "Comprimir PDF",
    compressCompleteTitle: "Compressão concluída!",
    compressReadyDesc: "Seu PDF foi otimizado e está pronto para baixar",
    originalSizeLabel: "Original",
    savedLabel: "Economizado",
    newSizeLabel: "Novo tamanho",
    downloadCompressedBtn: "Baixar PDF comprimido",
    compressAnotherBtn: "Comprimir outro arquivo",
    mergePdfsBtn: "Unir PDFs",
    splitPdfBtn: "Dividir PDF",
    batchCompressTip: "Precisa comprimir vários PDFs de uma vez?",
    tryBatchCompress: "Tentar compressão em lote",
    processingYourFile: "Processando seu arquivo",
    processingFiles: "Processando {n} arquivos",
    processedSecurely: "Seu arquivo está sendo processado com segurança",
    fileReadyDownload: "Seu arquivo está pronto para download",
    errorTitle: "Algo deu errado",
    errorMessage: "Ocorreu um erro ao processar seu arquivo. Por favor, tente novamente.",
    tryAgain: "Tentar novamente",
  },
  de: {
    home: "Startseite",
    allTools: "Alle Tools",
    blog: "Blog",
    pdfToWord: "PDF zu Word",
    merge: "PDF zusammenführen",
    compress: "Komprimieren",
    languageSwitcher: "Sprache",
    bannerText: "Diese Seite ist verfügbar auf",
    bannerSwitch: "Wechseln zu",
    bannerDismiss: "Schließen",
    uploadYourFiles: "Dateien hochladen",
    dropFilesHere: "Dateien hier ablegen!",
    releaseToUpload: "Loslassen zum Hochladen",
    tapToSelectFile: "Tippen, um Datei auszuwählen",
    tapToSelectFiles: "Tippen, um bis zu {n} Dateien auszuwählen",
    selectFile: "Datei auswählen",
    selectFiles: "Dateien auswählen",
    selectedFile: "Ausgewählte Datei",
    selectedFiles: "Ausgewählte Dateien ({n}/{max})",
    addMore: "Weitere hinzufügen",
    clearAll: "Alles löschen",
    secure: "Sicher",
    fast: "Schnell",
    free: "Kostenlos",
    hundredFree: "100% kostenlos",
    noLimits: "Keine Limits",
    noHiddenCosts: "Keine versteckten Kosten",
    sslEncrypted: "SSL-verschlüsselt",
    cloudPowered: "Cloud-basiert",
    unlimitedUse: "Unbegrenzte Nutzung",
    popularTools: "Beliebte Tools",
    menu: "Menü",
    openMenu: "Menü öffnen",
    convertFromPdf: "Aus PDF konvertieren",
    convertToPdf: "In PDF konvertieren",
    editPdf: "PDF bearbeiten",
    utilityTools: "Hilfs-Tools",
    compressPdf: "PDF komprimieren",
    freeToolsCount: "43+ kostenlose PDF-Tools",
    heroBadge: "43+ kostenlose PDF-Tools – Keine Registrierung",
    heroTitle: "Professionelle PDF-Tools",
    heroFree: "100% kostenlos online",
    heroSubtitle: "PDF-Dateien sofort konvertieren, zusammenführen, komprimieren und bearbeiten. Von Millionen vertraut.",
    heroDropFile: "Datei hier ablegen oder klicken zum Hochladen",
    heroChooseTool: "Dann wählen Sie, was Sie tun möchten",
    splitPdf: "PDF teilen",
    whatWouldYouLikeToDo: "Was möchten Sie tun?",
    viewAllTools: "Alle 43+ Tools anzeigen",
    featuredTools: "Ausgewählte Tools",
    mostPopular: "Am beliebtesten",
    allPdfTools: "Alle PDF-Tools",
    completeToolkit: "Komplettes Toolkit",
    allPdfToolsSubtitle: "Wählen Sie aus 43+ professionellen Tools für alle PDF-Anforderungen",
    simpleProcess: "Einfacher Prozess",
    howItWorks: "So funktioniert es",
    howItWorksSubtitle: "Drei einfache Schritte zur Transformation Ihrer PDF-Dateien",
    step1Title: "Tool auswählen",
    step2Title: "Datei hochladen",
    step3Title: "Ergebnis herunterladen",
    whyChooseUs: "Warum uns wählen",
    whyPdfHub24: "Warum PDF HUB 24?",
    whyChooseSubtitle: "Von Nutzern weltweit vertraut für schnelle, sichere PDF-Verarbeitung",
    viewAllArticles: "Alle Artikel anzeigen",
    featuredLabel: "Empfohlen",
    useTool: "Verwenden",
    gdprCompliant: "DSGVO-konform",
    noRegistration: "Keine Registrierung",
    showAllTools: "Alle {n} Tools anzeigen",
    showFewerTools: "Weniger Tools anzeigen",
    backToTools: "Zurück zu den Tools",
    euPrivacyLaw: "EU-Datenschutzrecht",
    noAccountNeeded: "Kein Konto erforderlich",
    uploadStep: "Hochladen",
    configureStep: "Konfigurieren",
    downloadStep: "Herunterladen",
    processingFile: "Ihre Datei wird verarbeitet...",
    successTitle: "Fertig!",
    downloadBtn: "Herunterladen",
    processAnotherBtn: "Weitere Datei verarbeiten",
    compressionLevelTitle: "Komprimierungsgrad wählen",
    compressionLevelDesc: "Wählen Sie den Grad, der Ihren Anforderungen am besten entspricht",
    lowCompression: "Niedrige Komprimierung",
    mediumCompression: "Mittlere Komprimierung",
    highCompression: "Hohe Komprimierung",
    recommended: "Empfohlen",
    qualityBadge: "Qualität",
    smallestBadge: "Kleinste",
    lowCompressionDesc: "Beste Qualität, etwas kleinere Dateigröße",
    mediumCompressionDesc: "Ausgewogenes Verhältnis zwischen Qualität und Dateigröße",
    highCompressionDesc: "Kleinste Dateigröße, reduzierte Bildqualität",
    compressPdfBtn: "PDF komprimieren",
    compressCompleteTitle: "Komprimierung abgeschlossen!",
    compressReadyDesc: "Ihr PDF wurde optimiert und ist zum Herunterladen bereit",
    originalSizeLabel: "Original",
    savedLabel: "Gespart",
    newSizeLabel: "Neue Größe",
    downloadCompressedBtn: "Komprimiertes PDF herunterladen",
    compressAnotherBtn: "Weitere Datei komprimieren",
    mergePdfsBtn: "PDFs zusammenführen",
    splitPdfBtn: "PDF teilen",
    batchCompressTip: "Möchten Sie mehrere PDFs gleichzeitig komprimieren?",
    tryBatchCompress: "Stapelkomprimierung ausprobieren",
    processingYourFile: "Ihre Datei wird verarbeitet",
    processingFiles: "{n} Dateien werden verarbeitet",
    processedSecurely: "Ihre Datei wird sicher verarbeitet",
    fileReadyDownload: "Ihre Datei ist zum Herunterladen bereit",
    errorTitle: "Etwas ist schiefgelaufen",
    errorMessage: "Bei der Verarbeitung Ihrer Datei ist ein Fehler aufgetreten. Bitte versuchen Sie es erneut.",
    tryAgain: "Erneut versuchen",
  },
  zh: {
    home: "首页",
    allTools: "所有工具",
    blog: "博客",
    pdfToWord: "PDF转Word",
    merge: "合并PDF",
    compress: "压缩",
    languageSwitcher: "语言",
    bannerText: "此页面可用语言",
    bannerSwitch: "切换到",
    bannerDismiss: "关闭",
    uploadYourFiles: "上传您的文件",
    dropFilesHere: "将文件拖放到此处！",
    releaseToUpload: "释放以上传",
    tapToSelectFile: "点击选择文件",
    tapToSelectFiles: "点击选择最多 {n} 个文件",
    selectFile: "选择文件",
    selectFiles: "选择多个文件",
    selectedFile: "已选文件",
    selectedFiles: "已选文件 ({n}/{max})",
    addMore: "添加更多",
    clearAll: "全部清除",
    secure: "安全",
    fast: "快速",
    free: "免费",
    hundredFree: "100% 免费",
    noLimits: "无限制",
    noHiddenCosts: "无隐藏费用",
    sslEncrypted: "SSL加密",
    cloudPowered: "云端支持",
    unlimitedUse: "无限使用",
    popularTools: "热门工具",
    menu: "菜单",
    openMenu: "打开菜单",
    convertFromPdf: "从PDF转换",
    convertToPdf: "转换为PDF",
    editPdf: "编辑PDF",
    utilityTools: "实用工具",
    compressPdf: "压缩PDF",
    freeToolsCount: "43+ 免费PDF工具",
    heroBadge: "43+ 免费PDF工具 - 无需注册",
    heroTitle: "专业PDF工具",
    heroFree: "100% 在线免费",
    heroSubtitle: "即时转换、合并、压缩和编辑PDF文件。全球数百万用户信赖。",
    heroDropFile: "将文件拖放到此处或点击上传",
    heroChooseTool: "然后选择您要执行的操作",
    splitPdf: "拆分PDF",
    whatWouldYouLikeToDo: "您想做什么？",
    viewAllTools: "查看所有 43+ 工具",
    featuredTools: "精选工具",
    mostPopular: "最受欢迎",
    allPdfTools: "所有PDF工具",
    completeToolkit: "完整工具集",
    allPdfToolsSubtitle: "从 43+ 专业工具中选择，满足您的所有PDF需求",
    simpleProcess: "简单流程",
    howItWorks: "使用方法",
    howItWorksSubtitle: "三个简单步骤转换您的PDF文件",
    step1Title: "选择工具",
    step2Title: "上传文件",
    step3Title: "下载结果",
    whyChooseUs: "为什么选择我们",
    whyPdfHub24: "为什么选择 PDF HUB 24？",
    whyChooseSubtitle: "全球用户信赖，提供快速、安全、可靠的PDF处理",
    viewAllArticles: "查看所有文章",
    featuredLabel: "精选",
    useTool: "使用",
    gdprCompliant: "符合GDPR",
    noRegistration: "无需注册",
    showAllTools: "显示所有 {n} 个工具",
    showFewerTools: "显示更少工具",
    backToTools: "返回工具",
    euPrivacyLaw: "欧盟隐私法",
    noAccountNeeded: "无需账户",
    uploadStep: "上传",
    configureStep: "配置",
    downloadStep: "下载",
    processingFile: "正在处理您的文件...",
    successTitle: "完成！",
    downloadBtn: "下载",
    processAnotherBtn: "处理另一个文件",
    compressionLevelTitle: "选择压缩级别",
    compressionLevelDesc: "选择最适合您需求的级别",
    lowCompression: "低压缩",
    mediumCompression: "中等压缩",
    highCompression: "高压缩",
    recommended: "推荐",
    qualityBadge: "质量",
    smallestBadge: "最小",
    lowCompressionDesc: "最佳质量，文件略小",
    mediumCompressionDesc: "质量与文件大小平衡",
    highCompressionDesc: "文件最小，图像质量降低",
    compressPdfBtn: "压缩PDF",
    compressCompleteTitle: "压缩完成！",
    compressReadyDesc: "您的PDF已优化，可以下载了",
    originalSizeLabel: "原始",
    savedLabel: "已节省",
    newSizeLabel: "新大小",
    downloadCompressedBtn: "下载压缩PDF",
    compressAnotherBtn: "压缩另一个文件",
    mergePdfsBtn: "合并PDF",
    splitPdfBtn: "拆分PDF",
    batchCompressTip: "需要一次性压缩多个PDF？",
    tryBatchCompress: "尝试批量压缩",
    processingYourFile: "正在处理您的文件",
    processingFiles: "正在处理 {n} 个文件",
    processedSecurely: "您的文件正在安全处理中",
    fileReadyDownload: "您的文件已准备好下载",
    errorTitle: "出现错误",
    errorMessage: "处理您的文件时发生错误，请重试。",
    tryAgain: "重试",
  },
  ja: {
    home: "ホーム",
    allTools: "全ツール",
    blog: "ブログ",
    pdfToWord: "PDFをWordに変換",
    merge: "PDFを結合",
    compress: "圧縮",
    languageSwitcher: "言語",
    bannerText: "このページは以下でも利用できます",
    bannerSwitch: "切り替え:",
    bannerDismiss: "閉じる",
    uploadYourFiles: "ファイルをアップロード",
    dropFilesHere: "ここにファイルをドロップ！",
    releaseToUpload: "離してアップロード",
    tapToSelectFile: "タップしてファイルを選択",
    tapToSelectFiles: "タップして最大 {n} ファイルを選択",
    selectFile: "ファイルを選択",
    selectFiles: "ファイルを選択",
    selectedFile: "選択済みファイル",
    selectedFiles: "選択済みファイル ({n}/{max})",
    addMore: "さらに追加",
    clearAll: "すべてクリア",
    secure: "安全",
    fast: "高速",
    free: "無料",
    hundredFree: "100% 無料",
    noLimits: "制限なし",
    noHiddenCosts: "隠れたコストなし",
    sslEncrypted: "SSL暗号化",
    cloudPowered: "クラウド対応",
    unlimitedUse: "無制限利用",
    popularTools: "人気ツール",
    menu: "メニュー",
    openMenu: "メニューを開く",
    convertFromPdf: "PDFから変換",
    convertToPdf: "PDFに変換",
    editPdf: "PDFを編集",
    utilityTools: "ユーティリティツール",
    compressPdf: "PDFを圧縮",
    freeToolsCount: "43種以上の無料PDFツール",
    heroBadge: "43種以上の無料PDFツール - 登録不要",
    heroTitle: "プロフェッショナルなPDFツール",
    heroFree: "100% 無料オンライン",
    heroSubtitle: "PDFファイルを即座に変換・結合・圧縮・編集。世界中の数百万ユーザーに信頼されています。",
    heroDropFile: "ここにファイルをドロップするかクリックしてアップロード",
    heroChooseTool: "次に実行する操作を選択してください",
    splitPdf: "PDFを分割",
    whatWouldYouLikeToDo: "何をしますか？",
    viewAllTools: "43種以上のツールをすべて表示",
    featuredTools: "おすすめツール",
    mostPopular: "最も人気",
    allPdfTools: "全PDFツール",
    completeToolkit: "完全ツールキット",
    allPdfToolsSubtitle: "あらゆるPDFニーズに対応した43種以上のプロツールから選択",
    simpleProcess: "シンプルな手順",
    howItWorks: "使い方",
    howItWorksSubtitle: "PDFファイルを変換する3つの簡単なステップ",
    step1Title: "ツールを選択",
    step2Title: "ファイルをアップロード",
    step3Title: "結果をダウンロード",
    whyChooseUs: "選ばれる理由",
    whyPdfHub24: "PDF HUB 24 を選ぶ理由",
    whyChooseSubtitle: "高速・安全・信頼できるPDF処理で世界中のユーザーに選ばれています",
    viewAllArticles: "すべての記事を見る",
    featuredLabel: "注目",
    useTool: "使用する",
    gdprCompliant: "GDPR準拠",
    noRegistration: "登録不要",
    showAllTools: "全 {n} ツールを表示",
    showFewerTools: "ツールを少なく表示",
    backToTools: "ツール一覧へ戻る",
    euPrivacyLaw: "EU個人情報保護法",
    noAccountNeeded: "アカウント不要",
    uploadStep: "アップロード",
    configureStep: "設定",
    downloadStep: "ダウンロード",
    processingFile: "ファイルを処理中...",
    successTitle: "完了！",
    downloadBtn: "ダウンロード",
    processAnotherBtn: "別のファイルを処理",
    compressionLevelTitle: "圧縮レベルを選択",
    compressionLevelDesc: "ニーズに最適なレベルを選択してください",
    lowCompression: "低圧縮",
    mediumCompression: "中圧縮",
    highCompression: "高圧縮",
    recommended: "おすすめ",
    qualityBadge: "品質",
    smallestBadge: "最小",
    lowCompressionDesc: "最高品質、ファイルサイズが少し小さくなります",
    mediumCompressionDesc: "品質とファイルサイズのバランス",
    highCompressionDesc: "最小サイズ、画像品質が低下",
    compressPdfBtn: "PDFを圧縮",
    compressCompleteTitle: "圧縮完了！",
    compressReadyDesc: "PDFが最適化され、ダウンロード準備ができました",
    originalSizeLabel: "元のサイズ",
    savedLabel: "節約",
    newSizeLabel: "新しいサイズ",
    downloadCompressedBtn: "圧縮PDFをダウンロード",
    compressAnotherBtn: "別のファイルを圧縮",
    mergePdfsBtn: "PDFを結合",
    splitPdfBtn: "PDFを分割",
    batchCompressTip: "複数のPDFを一度に圧縮したいですか？",
    tryBatchCompress: "バッチ圧縮を試す",
    processingYourFile: "ファイルを処理中",
    processingFiles: "{n} 個のファイルを処理中",
    processedSecurely: "ファイルは安全に処理されています",
    fileReadyDownload: "ファイルのダウンロード準備ができました",
    errorTitle: "エラーが発生しました",
    errorMessage: "ファイルの処理中にエラーが発生しました。もう一度お試しください。",
    tryAgain: "もう一度試す",
  },
  id: {
    home: "Beranda",
    allTools: "Semua Alat",
    blog: "Blog",
    pdfToWord: "PDF ke Word",
    merge: "Gabungkan PDF",
    compress: "Kompres",
    languageSwitcher: "Bahasa",
    bannerText: "Halaman ini tersedia dalam",
    bannerSwitch: "Beralih ke",
    bannerDismiss: "Tutup",
    uploadYourFiles: "Unggah File Anda",
    dropFilesHere: "Taruh file Anda di sini!",
    releaseToUpload: "Lepaskan untuk mengunggah",
    tapToSelectFile: "Ketuk untuk memilih file Anda",
    tapToSelectFiles: "Ketuk untuk memilih hingga {n} file",
    selectFile: "Pilih File",
    selectFiles: "Pilih File",
    selectedFile: "File Dipilih",
    selectedFiles: "File Dipilih ({n}/{max})",
    addMore: "Tambah Lagi",
    clearAll: "Hapus Semua",
    secure: "Aman",
    fast: "Cepat",
    free: "Gratis",
    hundredFree: "100% Gratis",
    noLimits: "Tanpa Batas",
    noHiddenCosts: "Tanpa biaya tersembunyi",
    sslEncrypted: "Terenkripsi SSL",
    cloudPowered: "Berbasis Cloud",
    unlimitedUse: "Penggunaan tak terbatas",
    popularTools: "Alat Populer",
    menu: "Menu",
    openMenu: "Buka menu",
    convertFromPdf: "Konversi dari PDF",
    convertToPdf: "Konversi ke PDF",
    editPdf: "Edit PDF",
    utilityTools: "Alat Utilitas",
    compressPdf: "Kompres PDF",
    freeToolsCount: "43+ Alat PDF Gratis",
    heroBadge: "43+ Alat PDF Gratis - Tanpa Registrasi",
    heroTitle: "Alat PDF Profesional",
    heroFree: "100% Gratis Online",
    heroSubtitle: "Konversi, gabungkan, kompres, dan edit file PDF secara instan. Dipercaya jutaan pengguna di seluruh dunia.",
    heroDropFile: "Taruh file Anda di sini atau klik untuk mengunggah",
    heroChooseTool: "Kemudian pilih apa yang ingin Anda lakukan",
    splitPdf: "Pisahkan PDF",
    whatWouldYouLikeToDo: "Apa yang ingin Anda lakukan?",
    viewAllTools: "Lihat Semua 43+ Alat",
    featuredTools: "Alat Unggulan",
    mostPopular: "Paling Populer",
    allPdfTools: "Semua Alat PDF",
    completeToolkit: "Toolkit Lengkap",
    allPdfToolsSubtitle: "Pilih dari 43+ alat profesional untuk semua kebutuhan PDF Anda",
    simpleProcess: "Proses Sederhana",
    howItWorks: "Cara Kerja",
    howItWorksSubtitle: "Tiga langkah sederhana untuk mengubah file PDF Anda",
    step1Title: "Pilih Alat Anda",
    step2Title: "Unggah File Anda",
    step3Title: "Unduh Hasilnya",
    whyChooseUs: "Mengapa Memilih Kami",
    whyPdfHub24: "Mengapa PDF HUB 24?",
    whyChooseSubtitle: "Dipercaya pengguna di seluruh dunia untuk pemrosesan PDF yang cepat, aman, dan andal",
    viewAllArticles: "Lihat Semua Artikel",
    featuredLabel: "Unggulan",
    useTool: "Gunakan",
    gdprCompliant: "Sesuai GDPR",
    noRegistration: "Tanpa Registrasi",
    showAllTools: "Tampilkan semua {n} alat",
    showFewerTools: "Tampilkan lebih sedikit alat",
    backToTools: "Kembali ke Alat",
    euPrivacyLaw: "Undang-undang Privasi UE",
    noAccountNeeded: "Tidak perlu akun",
    uploadStep: "Unggah",
    configureStep: "Konfigurasi",
    downloadStep: "Unduh",
    processingFile: "Memproses file Anda...",
    successTitle: "Selesai!",
    downloadBtn: "Unduh",
    processAnotherBtn: "Proses File Lain",
    compressionLevelTitle: "Pilih Tingkat Kompresi",
    compressionLevelDesc: "Pilih tingkat yang paling sesuai dengan kebutuhan Anda",
    lowCompression: "Kompresi Rendah",
    mediumCompression: "Kompresi Sedang",
    highCompression: "Kompresi Tinggi",
    recommended: "Disarankan",
    qualityBadge: "Kualitas",
    smallestBadge: "Terkecil",
    lowCompressionDesc: "Kualitas terbaik, ukuran file sedikit lebih kecil",
    mediumCompressionDesc: "Keseimbangan antara kualitas dan ukuran file",
    highCompressionDesc: "Ukuran terkecil, kualitas gambar berkurang",
    compressPdfBtn: "Kompres PDF",
    compressCompleteTitle: "Kompresi Selesai!",
    compressReadyDesc: "PDF Anda telah dioptimalkan dan siap diunduh",
    originalSizeLabel: "Asli",
    savedLabel: "Dihemat",
    newSizeLabel: "Ukuran Baru",
    downloadCompressedBtn: "Unduh PDF Terkompresi",
    compressAnotherBtn: "Kompres File Lain",
    mergePdfsBtn: "Gabungkan PDF",
    splitPdfBtn: "Pisahkan PDF",
    batchCompressTip: "Perlu mengompres beberapa PDF sekaligus?",
    tryBatchCompress: "Coba Kompres Massal",
    processingYourFile: "Memproses file Anda",
    processingFiles: "Memproses {n} file",
    processedSecurely: "File Anda sedang diproses dengan aman",
    fileReadyDownload: "File Anda siap untuk diunduh",
    errorTitle: "Terjadi kesalahan",
    errorMessage: "Terjadi kesalahan saat memproses file Anda. Silakan coba lagi.",
    tryAgain: "Coba lagi",
  },
  ru: {
    home: "Главная",
    allTools: "Все инструменты",
    blog: "Блог",
    pdfToWord: "PDF в Word",
    merge: "Объединить PDF",
    compress: "Сжать",
    languageSwitcher: "Язык",
    bannerText: "Эта страница доступна на",
    bannerSwitch: "Переключить на",
    bannerDismiss: "Закрыть",
    uploadYourFiles: "Загрузите ваши файлы",
    dropFilesHere: "Перетащите файлы сюда!",
    releaseToUpload: "Отпустите для загрузки",
    tapToSelectFile: "Нажмите для выбора файла",
    tapToSelectFiles: "Нажмите для выбора до {n} файлов",
    selectFile: "Выбрать файл",
    selectFiles: "Выбрать файлы",
    selectedFile: "Выбранный файл",
    selectedFiles: "Выбранные файлы ({n}/{max})",
    addMore: "Добавить ещё",
    clearAll: "Очистить всё",
    secure: "Безопасно",
    fast: "Быстро",
    free: "Бесплатно",
    hundredFree: "100% бесплатно",
    noLimits: "Без ограничений",
    noHiddenCosts: "Без скрытых платежей",
    sslEncrypted: "SSL-шифрование",
    cloudPowered: "Облачные технологии",
    unlimitedUse: "Безлимитное использование",
    popularTools: "Популярные инструменты",
    menu: "Меню",
    openMenu: "Открыть меню",
    convertFromPdf: "Конвертировать из PDF",
    convertToPdf: "Конвертировать в PDF",
    editPdf: "Редактировать PDF",
    utilityTools: "Утилиты",
    compressPdf: "Сжать PDF",
    freeToolsCount: "43+ бесплатных PDF инструментов",
    heroBadge: "43+ бесплатных PDF инструментов — без регистрации",
    heroTitle: "Профессиональные PDF инструменты",
    heroFree: "100% бесплатно онлайн",
    heroSubtitle: "Мгновенно конвертируйте, объединяйте, сжимайте и редактируйте PDF. Доверяют миллионы по всему миру.",
    heroDropFile: "Перетащите файл сюда или нажмите для загрузки",
    heroChooseTool: "Затем выберите, что хотите сделать",
    splitPdf: "Разделить PDF",
    whatWouldYouLikeToDo: "Что вы хотите сделать?",
    viewAllTools: "Все 43+ инструментов",
    featuredTools: "Рекомендуемые инструменты",
    mostPopular: "Самые популярные",
    allPdfTools: "Все PDF инструменты",
    completeToolkit: "Полный набор инструментов",
    allPdfToolsSubtitle: "Выбирайте из 43+ профессиональных инструментов для PDF",
    simpleProcess: "Простой процесс",
    howItWorks: "Как это работает",
    howItWorksSubtitle: "Три простых шага для преобразования PDF файлов",
    step1Title: "Выберите инструмент",
    step2Title: "Загрузите файл",
    step3Title: "Скачайте результат",
    whyChooseUs: "Почему мы",
    whyPdfHub24: "Почему PDF HUB 24?",
    whyChooseSubtitle: "Доверяют пользователи по всему миру за быструю, безопасную обработку PDF",
    viewAllArticles: "Все статьи",
    featuredLabel: "Рекомендуем",
    useTool: "Использовать",
    gdprCompliant: "Соответствие GDPR",
    noRegistration: "Без регистрации",
    showAllTools: "Показать все {n} инструментов",
    showFewerTools: "Показать меньше",
    backToTools: "Вернуться к инструментам",
    euPrivacyLaw: "Закон ЕС о конфиденциальности",
    noAccountNeeded: "Без учётной записи",
    uploadStep: "Загрузить",
    configureStep: "Настроить",
    downloadStep: "Скачать",
    processingFile: "Обработка вашего файла...",
    successTitle: "Готово!",
    downloadBtn: "Скачать",
    processAnotherBtn: "Обработать другой файл",
    compressionLevelTitle: "Выберите уровень сжатия",
    compressionLevelDesc: "Выберите уровень, подходящий для ваших нужд",
    lowCompression: "Слабое сжатие",
    mediumCompression: "Среднее сжатие",
    highCompression: "Сильное сжатие",
    recommended: "Рекомендуется",
    qualityBadge: "Качество",
    smallestBadge: "Минимальный",
    lowCompressionDesc: "Лучшее качество, немного меньший размер файла",
    mediumCompressionDesc: "Баланс между качеством и размером файла",
    highCompressionDesc: "Минимальный размер, сниженное качество изображения",
    compressPdfBtn: "Сжать PDF",
    compressCompleteTitle: "Сжатие завершено!",
    compressReadyDesc: "Ваш PDF оптимизирован и готов к скачиванию",
    originalSizeLabel: "Исходный",
    savedLabel: "Сохранено",
    newSizeLabel: "Новый размер",
    downloadCompressedBtn: "Скачать сжатый PDF",
    compressAnotherBtn: "Сжать другой файл",
    mergePdfsBtn: "Объединить PDF",
    splitPdfBtn: "Разделить PDF",
    batchCompressTip: "Нужно сжать несколько PDF за раз?",
    tryBatchCompress: "Попробовать пакетное сжатие",
    processingYourFile: "Обработка вашего файла",
    processingFiles: "Обработка {n} файлов",
    processedSecurely: "Ваш файл обрабатывается безопасно",
    fileReadyDownload: "Ваш файл готов к скачиванию",
    errorTitle: "Что-то пошло не так",
    errorMessage: "При обработке файла произошла ошибка. Пожалуйста, попробуйте ещё раз.",
    tryAgain: "Попробовать снова",
  },
  it: {
    home: "Home",
    allTools: "Tutti gli strumenti",
    blog: "Blog",
    pdfToWord: "Da PDF a Word",
    merge: "Unisci PDF",
    compress: "Comprimi",
    languageSwitcher: "Lingua",
    bannerText: "Questa pagina è disponibile in",
    bannerSwitch: "Passa a",
    bannerDismiss: "Chiudi",
    uploadYourFiles: "Carica i tuoi file",
    dropFilesHere: "Trascina i tuoi file qui!",
    releaseToUpload: "Rilascia per caricare",
    tapToSelectFile: "Tocca per selezionare il file",
    tapToSelectFiles: "Tocca per selezionare fino a {n} file",
    selectFile: "Seleziona file",
    selectFiles: "Seleziona file",
    selectedFile: "File selezionato",
    selectedFiles: "File selezionati ({n}/{max})",
    addMore: "Aggiungi altri",
    clearAll: "Cancella tutto",
    secure: "Sicuro",
    fast: "Veloce",
    free: "Gratuito",
    hundredFree: "100% Gratuito",
    noLimits: "Nessun limite",
    noHiddenCosts: "Nessun costo nascosto",
    sslEncrypted: "Crittografia SSL",
    cloudPowered: "Basato su cloud",
    unlimitedUse: "Utilizzo illimitato",
    popularTools: "Strumenti popolari",
    menu: "Menu",
    openMenu: "Apri menu",
    convertFromPdf: "Converti da PDF",
    convertToPdf: "Converti in PDF",
    editPdf: "Modifica PDF",
    utilityTools: "Strumenti di utilità",
    compressPdf: "Comprimi PDF",
    freeToolsCount: "43+ strumenti PDF gratuiti",
    heroBadge: "43+ strumenti PDF gratuiti - Nessuna registrazione",
    heroTitle: "Strumenti PDF professionali",
    heroFree: "100% gratuito online",
    heroSubtitle: "Converti, unisci, comprimi e modifica file PDF all'istante. Scelto da milioni di utenti in tutto il mondo.",
    heroDropFile: "Trascina il tuo file qui o clicca per caricare",
    heroChooseTool: "Poi scegli cosa vuoi fare",
    splitPdf: "Dividi PDF",
    whatWouldYouLikeToDo: "Cosa vorresti fare?",
    viewAllTools: "Vedi tutti i 43+ strumenti",
    featuredTools: "Strumenti in evidenza",
    mostPopular: "Più popolari",
    allPdfTools: "Tutti gli strumenti PDF",
    completeToolkit: "Kit completo",
    allPdfToolsSubtitle: "Scegli tra 43+ strumenti professionali per tutte le tue esigenze PDF",
    simpleProcess: "Processo semplice",
    howItWorks: "Come funziona",
    howItWorksSubtitle: "Tre semplici passaggi per trasformare i tuoi file PDF",
    step1Title: "Scegli il tuo strumento",
    step2Title: "Carica il tuo file",
    step3Title: "Scarica il risultato",
    whyChooseUs: "Perché sceglierci",
    whyPdfHub24: "Perché PDF HUB 24?",
    whyChooseSubtitle: "Scelto dagli utenti di tutto il mondo per l'elaborazione PDF rapida, sicura e affidabile",
    viewAllArticles: "Vedi tutti gli articoli",
    featuredLabel: "In evidenza",
    useTool: "Usa",
    gdprCompliant: "Conforme GDPR",
    noRegistration: "Nessuna registrazione",
    showAllTools: "Mostra tutti i {n} strumenti",
    showFewerTools: "Mostra meno strumenti",
    backToTools: "Torna agli strumenti",
    euPrivacyLaw: "Legge sulla privacy UE",
    noAccountNeeded: "Nessun account necessario",
    uploadStep: "Carica",
    configureStep: "Configura",
    downloadStep: "Scarica",
    processingFile: "Elaborazione del file...",
    successTitle: "Fatto!",
    downloadBtn: "Scarica",
    processAnotherBtn: "Elabora un altro file",
    compressionLevelTitle: "Scegli il livello di compressione",
    compressionLevelDesc: "Seleziona il livello più adatto alle tue esigenze",
    lowCompression: "Compressione bassa",
    mediumCompression: "Compressione media",
    highCompression: "Compressione alta",
    recommended: "Consigliato",
    qualityBadge: "Qualità",
    smallestBadge: "Minimo",
    lowCompressionDesc: "Migliore qualità, dimensione file leggermente ridotta",
    mediumCompressionDesc: "Equilibrio tra qualità e dimensione del file",
    highCompressionDesc: "Dimensione minima, qualità immagine ridotta",
    compressPdfBtn: "Comprimi PDF",
    compressCompleteTitle: "Compressione completata!",
    compressReadyDesc: "Il tuo PDF è stato ottimizzato ed è pronto per il download",
    originalSizeLabel: "Originale",
    savedLabel: "Risparmiato",
    newSizeLabel: "Nuova dimensione",
    downloadCompressedBtn: "Scarica PDF compresso",
    compressAnotherBtn: "Comprimi un altro file",
    mergePdfsBtn: "Unisci PDF",
    splitPdfBtn: "Dividi PDF",
    batchCompressTip: "Hai bisogno di comprimere più PDF contemporaneamente?",
    tryBatchCompress: "Prova la compressione in batch",
    processingYourFile: "Elaborazione del tuo file",
    processingFiles: "Elaborazione di {n} file",
    processedSecurely: "Il tuo file viene elaborato in modo sicuro",
    fileReadyDownload: "Il tuo file è pronto per il download",
    errorTitle: "Qualcosa è andato storto",
    errorMessage: "Si è verificato un errore durante l'elaborazione del file. Riprova.",
    tryAgain: "Riprova",
  },
  ur: {
    home: "ہوم",
    allTools: "تمام ٹولز",
    blog: "بلاگ",
    pdfToWord: "PDF سے Word",
    merge: "PDF ملائیں",
    compress: "کمپریس کریں",
    languageSwitcher: "زبان",
    bannerText: "یہ صفحہ دستیاب ہے",
    bannerSwitch: "بدلیں",
    bannerDismiss: "بند کریں",
    uploadYourFiles: "اپنی فائلیں اپلوڈ کریں",
    dropFilesHere: "فائلیں یہاں چھوڑیں!",
    releaseToUpload: "اپلوڈ کرنے کے لیے چھوڑیں",
    tapToSelectFile: "فائل منتخب کرنے کے لیے تھپتھپائیں",
    tapToSelectFiles: "{n} فائلیں منتخب کرنے کے لیے تھپتھپائیں",
    selectFile: "فائل منتخب کریں",
    selectFiles: "فائلیں منتخب کریں",
    selectedFile: "منتخب فائل",
    selectedFiles: "منتخب فائلیں ({n}/{max})",
    addMore: "مزید شامل کریں",
    clearAll: "سب صاف کریں",
    secure: "محفوظ",
    fast: "تیز",
    free: "مفت",
    hundredFree: "100% مفت",
    noLimits: "کوئی حد نہیں",
    noHiddenCosts: "کوئی پوشیدہ لاگت نہیں",
    sslEncrypted: "SSL انکرپٹڈ",
    cloudPowered: "کلاؤڈ پاورڈ",
    unlimitedUse: "لامحدود استعمال",
    popularTools: "مشہور ٹولز",
    menu: "مینو",
    openMenu: "مینو کھولیں",
    convertFromPdf: "PDF سے تبدیل کریں",
    convertToPdf: "PDF میں تبدیل کریں",
    editPdf: "PDF ترمیم کریں",
    utilityTools: "یوٹیلیٹی ٹولز",
    compressPdf: "PDF کمپریس کریں",
    freeToolsCount: "43+ مفت PDF ٹولز",
    heroBadge: "43+ مفت PDF ٹولز - رجسٹریشن کی ضرورت نہیں",
    heroTitle: "پیشہ ورانہ PDF ٹولز",
    heroFree: "100% آن لائن مفت",
    heroSubtitle: "PDF فائلوں کو فوری طور پر تبدیل، ملائیں، کمپریس اور ترمیم کریں۔ دنیا بھر کے لاکھوں صارفین کا اعتماد۔",
    heroDropFile: "یہاں فائل چھوڑیں یا اپلوڈ کرنے کے لیے کلک کریں",
    heroChooseTool: "پھر منتخب کریں کہ آپ کیا کرنا چاہتے ہیں",
    splitPdf: "PDF تقسیم کریں",
    whatWouldYouLikeToDo: "آپ کیا کرنا چاہیں گے؟",
    viewAllTools: "تمام 43+ ٹولز دیکھیں",
    featuredTools: "نمایاں ٹولز",
    mostPopular: "سب سے مشہور",
    allPdfTools: "تمام PDF ٹولز",
    completeToolkit: "مکمل ٹول کٹ",
    allPdfToolsSubtitle: "آپ کی تمام PDF ضروریات کے لیے 43+ پیشہ ورانہ ٹولز میں سے انتخاب کریں",
    simpleProcess: "آسان عمل",
    howItWorks: "یہ کیسے کام کرتا ہے",
    howItWorksSubtitle: "اپنی PDF فائلوں کو تبدیل کرنے کے لیے تین آسان مراحل",
    step1Title: "اپنا ٹول منتخب کریں",
    step2Title: "اپنی فائل اپلوڈ کریں",
    step3Title: "نتیجہ ڈاؤن لوڈ کریں",
    whyChooseUs: "ہمیں کیوں چنیں",
    whyPdfHub24: "PDF HUB 24 کیوں؟",
    whyChooseSubtitle: "تیز، محفوظ اور قابل اعتماد PDF پروسیسنگ کے لیے دنیا بھر کے صارفین کا اعتماد",
    viewAllArticles: "تمام مضامین دیکھیں",
    featuredLabel: "نمایاں",
    useTool: "استعمال کریں",
    gdprCompliant: "GDPR کے مطابق",
    noRegistration: "رجسٹریشن نہیں",
    showAllTools: "تمام {n} ٹولز دکھائیں",
    showFewerTools: "کم ٹولز دکھائیں",
    backToTools: "ٹولز پر واپس جائیں",
    euPrivacyLaw: "یورپی یونین پرائیویسی قانون",
    noAccountNeeded: "اکاؤنٹ کی ضرورت نہیں",
    uploadStep: "اپلوڈ",
    configureStep: "ترتیب",
    downloadStep: "ڈاؤن لوڈ",
    processingFile: "آپ کی فائل پروسیس ہو رہی ہے...",
    successTitle: "مکمل!",
    downloadBtn: "ڈاؤن لوڈ",
    processAnotherBtn: "دوسری فائل پروسیس کریں",
    compressionLevelTitle: "کمپریشن لیول منتخب کریں",
    compressionLevelDesc: "اپنی ضرورت کے مطابق لیول منتخب کریں",
    lowCompression: "کم کمپریشن",
    mediumCompression: "درمیانہ کمپریشن",
    highCompression: "زیادہ کمپریشن",
    recommended: "تجویز کردہ",
    qualityBadge: "معیار",
    smallestBadge: "سب سے چھوٹا",
    lowCompressionDesc: "بہترین معیار، فائل کا سائز تھوڑا چھوٹا",
    mediumCompressionDesc: "معیار اور سائز میں توازن",
    highCompressionDesc: "سب سے چھوٹا سائز، تصویر کا معیار کم",
    compressPdfBtn: "PDF کمپریس کریں",
    compressCompleteTitle: "کمپریشن مکمل!",
    compressReadyDesc: "آپ کی PDF بہتر بنائی گئی ہے اور ڈاؤن لوڈ کے لیے تیار ہے",
    originalSizeLabel: "اصلی",
    savedLabel: "بچایا",
    newSizeLabel: "نیا سائز",
    downloadCompressedBtn: "کمپریسڈ PDF ڈاؤن لوڈ کریں",
    compressAnotherBtn: "دوسری فائل کمپریس کریں",
    mergePdfsBtn: "PDF ملائیں",
    splitPdfBtn: "PDF تقسیم کریں",
    batchCompressTip: "ایک ساتھ متعدد PDF کمپریس کرنے کی ضرورت ہے؟",
    tryBatchCompress: "بیچ کمپریس آزمائیں",
    processingYourFile: "آپ کی فائل پروسیس ہو رہی ہے",
    processingFiles: "{n} فائلیں پروسیس ہو رہی ہیں",
    processedSecurely: "آپ کی فائل محفوظ طریقے سے پروسیس ہو رہی ہے",
    fileReadyDownload: "آپ کی فائل ڈاؤن لوڈ کے لیے تیار ہے",
    errorTitle: "کچھ غلط ہو گیا",
    errorMessage: "آپ کی فائل پروسیس کرتے وقت خرابی ہوئی۔ براہ کرم دوبارہ کوشش کریں۔",
    tryAgain: "دوبارہ کوشش کریں",
  },
};

export function t(lang: string, key: string): string {
  return UI_TRANSLATIONS[lang]?.[key] || UI_TRANSLATIONS["en"][key] || key;
}

export function tFormat(lang: string, key: string, vars: Record<string, string | number>): string {
  let str = t(lang, key);
  for (const [k, v] of Object.entries(vars)) {
    str = str.replace(`{${k}}`, String(v));
  }
  return str;
}

export const TOOL_TITLE_TRANSLATIONS: Record<string, Partial<Record<string, string>>> = {
  "merge":          { ur: "PDF ملائیں",              es: "Unir PDF",               ar: "دمج PDF",                hi: "PDF जोड़ें",            fr: "Fusionner PDF",          pt: "Unir PDF",             de: "PDF zusammenführen",    zh: "合并PDF",          ja: "PDFを結合",          id: "Gabungkan PDF",       ru: "Объединить PDF",        it: "Unisci PDF" },
  "split":          { ur: "PDF تقسیم کریں",              es: "Dividir PDF",             ar: "تقسيم PDF",              hi: "PDF विभाजित करें",     fr: "Diviser PDF",            pt: "Dividir PDF",          de: "PDF teilen",            zh: "拆分PDF",          ja: "PDFを分割",          id: "Pisahkan PDF",        ru: "Разделить PDF",         it: "Dividi PDF" },
  "compress":       { ur: "PDF کمپریس کریں",              es: "Comprimir PDF",           ar: "ضغط PDF",                hi: "PDF कम्प्रेस",          fr: "Compresser PDF",         pt: "Comprimir PDF",        de: "PDF komprimieren",      zh: "压缩PDF",          ja: "PDFを圧縮",          id: "Kompres PDF",         ru: "Сжать PDF",             it: "Comprimi PDF" },
  "pdf-to-word":    { ur: "PDF سے Word",              es: "PDF a Word",              ar: "PDF إلى Word",           hi: "PDF से Word",          fr: "PDF en Word",            pt: "PDF para Word",        de: "PDF zu Word",           zh: "PDF转Word",        ja: "PDFをWordに変換",    id: "PDF ke Word",         ru: "PDF в Word",            it: "Da PDF a Word" },
  "pdf-to-jpg":     { ur: "PDF سے JPG",              es: "PDF a JPG",               ar: "PDF إلى JPG",            hi: "PDF से JPG",           fr: "PDF en JPG",             pt: "PDF para JPG",         de: "PDF zu JPG",            zh: "PDF转JPG",         ja: "PDFをJPGに変換",     id: "PDF ke JPG",          ru: "PDF в JPG",             it: "Da PDF a JPG" },
  "pdf-to-png":     { ur: "PDF سے PNG",              es: "PDF a PNG",               ar: "PDF إلى PNG",            hi: "PDF से PNG",           fr: "PDF en PNG",             pt: "PDF para PNG",         de: "PDF zu PNG",            zh: "PDF转PNG",         ja: "PDFをPNGに変換",     id: "PDF ke PNG",          ru: "PDF в PNG",             it: "Da PDF a PNG" },
  "pdf-to-excel":   { ur: "PDF سے Excel",              es: "PDF a Excel",             ar: "PDF إلى إكسيل",          hi: "PDF से Excel",         fr: "PDF en Excel",           pt: "PDF para Excel",       de: "PDF zu Excel",          zh: "PDF转Excel",       ja: "PDFをExcelに変換",   id: "PDF ke Excel",        ru: "PDF в Excel",           it: "Da PDF a Excel" },
  "pdf-to-ppt":     { ur: "PDF سے PowerPoint",              es: "PDF a PowerPoint",        ar: "PDF إلى PowerPoint",     hi: "PDF से PowerPoint",    fr: "PDF en PowerPoint",      pt: "PDF para PowerPoint",  de: "PDF zu PowerPoint",     zh: "PDF转PPT",         ja: "PDFをPPTに変換",     id: "PDF ke PowerPoint",   ru: "PDF в PowerPoint",      it: "Da PDF a PowerPoint" },
  "jpg-to-pdf":     { ur: "JPG سے PDF",              es: "JPG a PDF",               ar: "JPG إلى PDF",            hi: "JPG से PDF",           fr: "JPG en PDF",             pt: "JPG para PDF",         de: "JPG zu PDF",            zh: "JPG转PDF",         ja: "JPGをPDFに変換",     id: "JPG ke PDF",          ru: "JPG в PDF",             it: "Da JPG a PDF" },
  "png-to-pdf":     { ur: "PNG سے PDF",              es: "PNG a PDF",               ar: "PNG إلى PDF",            hi: "PNG से PDF",           fr: "PNG en PDF",             pt: "PNG para PDF",         de: "PNG zu PDF",            zh: "PNG转PDF",         ja: "PNGをPDFに変換",     id: "PNG ke PDF",          ru: "PNG в PDF",             it: "Da PNG a PDF" },
  "word-to-pdf":    { ur: "Word سے PDF",              es: "Word a PDF",              ar: "وورد إلى PDF",           hi: "Word से PDF",          fr: "Word en PDF",            pt: "Word para PDF",        de: "Word zu PDF",           zh: "Word转PDF",        ja: "WordをPDFに変換",    id: "Word ke PDF",         ru: "Word в PDF",            it: "Da Word a PDF" },
  "excel-to-pdf":   { ur: "Excel سے PDF",              es: "Excel a PDF",             ar: "إكسيل إلى PDF",          hi: "Excel से PDF",         fr: "Excel en PDF",           pt: "Excel para PDF",       de: "Excel zu PDF",          zh: "Excel转PDF",       ja: "ExcelをPDFに変換",   id: "Excel ke PDF",        ru: "Excel в PDF",           it: "Da Excel a PDF" },
  "ppt-to-pdf":     { ur: "PowerPoint سے PDF",              es: "PowerPoint a PDF",        ar: "PowerPoint إلى PDF",     hi: "PowerPoint से PDF",    fr: "PowerPoint en PDF",      pt: "PowerPoint para PDF",  de: "PowerPoint zu PDF",     zh: "PPT转PDF",         ja: "PPTをPDFに変換",     id: "PowerPoint ke PDF",   ru: "PowerPoint в PDF",      it: "Da PowerPoint a PDF" },
  "protect":        { ur: "PDF محفوظ کریں",              es: "Proteger PDF",            ar: "حماية PDF",              hi: "PDF सुरक्षित करें",     fr: "Protéger PDF",           pt: "Proteger PDF",         de: "PDF schützen",          zh: "保护PDF",          ja: "PDFを保護",          id: "Lindungi PDF",        ru: "Защитить PDF",          it: "Proteggi PDF" },
  "unlock":         { ur: "PDF انلاک کریں",              es: "Desbloquear PDF",         ar: "فتح قفل PDF",            hi: "PDF अनलॉक करें",       fr: "Déverrouiller PDF",      pt: "Desbloquear PDF",      de: "PDF entsperren",        zh: "解锁PDF",          ja: "PDFをロック解除",    id: "Buka Kunci PDF",      ru: "Разблокировать PDF",    it: "Sblocca PDF" },
  "sign":           { ur: "PDF سائن کریں",              es: "Firmar PDF",              ar: "توقيع PDF",              hi: "PDF साइन करें",         fr: "Signer PDF",             pt: "Assinar PDF",          de: "PDF unterschreiben",    zh: "签名PDF",          ja: "PDFに署名",          id: "Tanda Tangani PDF",   ru: "Подписать PDF",         it: "Firma PDF" },
  "rotate":         { ur: "PDF گھمائیں",              es: "Rotar PDF",               ar: "تدوير PDF",              hi: "PDF घुमाएं",           fr: "Pivoter PDF",            pt: "Rotacionar PDF",       de: "PDF drehen",            zh: "旋转PDF",          ja: "PDFを回転",          id: "Putar PDF",           ru: "Повернуть PDF",         it: "Ruota PDF" },
  "watermark":      { ur: "PDF واٹر مارک",              es: "Marca de agua PDF",       ar: "علامة مائية PDF",        hi: "PDF वॉटरमार्क",        fr: "Filigrane PDF",          pt: "Marca d'água PDF",     de: "PDF Wasserzeichen",     zh: "PDF水印",          ja: "PDF透かし",          id: "Watermark PDF",       ru: "Водяной знак PDF",      it: "Filigrana PDF" },
  "grayscale":      { ur: "PDF گرے اسکیل",              es: "PDF en escala de grises", ar: "PDF رمادي",              hi: "PDF ग्रेस्केल",         fr: "PDF en niveaux de gris", pt: "PDF em tons de cinza", de: "PDF in Graustufen",     zh: "PDF转灰度",        ja: "PDFをグレー変換",    id: "PDF Skala Abu-abu",   ru: "PDF в оттенках серого", it: "PDF in scala di grigi" },
  "ocr-pdf":        { ur: "OCR PDF",              es: "OCR PDF",                 ar: "OCR PDF",                hi: "OCR PDF",               fr: "OCR PDF",                pt: "OCR PDF",              de: "OCR PDF",               zh: "OCR PDF",          ja: "OCR PDF",            id: "OCR PDF",             ru: "OCR PDF",               it: "OCR PDF" },
  "image-compressor":{ ur: "تصویر کمپریس کریں",              es: "Comprimir imágenes",     ar: "ضغط الصور",              hi: "इमेज कम्प्रेस",         fr: "Compresser images",      pt: "Comprimir imagens",    de: "Bilder komprimieren",   zh: "压缩图片",         ja: "画像を圧縮",         id: "Kompres Gambar",      ru: "Сжать изображения",     it: "Comprimi immagini" },
  "image-resize":   { ur: "تصویر کا سائز بدلیں",              es: "Redimensionar imagen",    ar: "تغيير حجم الصورة",      hi: "इमेज रीसाइज़",          fr: "Redimensionner image",   pt: "Redimensionar imagem", de: "Bildgröße ändern",      zh: "调整图片大小",     ja: "画像をリサイズ",     id: "Ubah Ukuran Gambar",  ru: "Изменить размер",       it: "Ridimensiona immagine" },
  "image-crop":     { ur: "تصویر کراپ کریں",              es: "Recortar imagen",         ar: "قص الصورة",              hi: "इमेज क्रॉप",           fr: "Rogner image",           pt: "Recortar imagem",      de: "Bild zuschneiden",      zh: "裁剪图片",         ja: "画像を切り取り",     id: "Pangkas Gambar",      ru: "Обрезать изображение",  it: "Ritaglia immagine" },
  "image-convert":  { ur: "تصویر تبدیل کریں",              es: "Convertir imagen",        ar: "تحويل الصورة",           hi: "इमेज कन्वर्ट",          fr: "Convertir image",        pt: "Converter imagem",     de: "Bild konvertieren",     zh: "转换图片",         ja: "画像を変換",         id: "Konversi Gambar",     ru: "Конвертировать фото",   it: "Converti immagine" },
  "edit-pdf":       { ur: "PDF ترمیم کریں",              es: "Editar PDF",              ar: "تعديل PDF",              hi: "PDF संपादित करें",      fr: "Modifier PDF",           pt: "Editar PDF",           de: "PDF bearbeiten",        zh: "编辑PDF",          ja: "PDFを編集",          id: "Edit PDF",            ru: "Редактировать PDF",     it: "Modifica PDF" },
  "annotate":       { ur: "PDF پر نوٹ لکھیں",              es: "Anotar PDF",              ar: "تعليق على PDF",          hi: "PDF एनोटेट",           fr: "Annoter PDF",            pt: "Anotar PDF",           de: "PDF annotieren",        zh: "注释PDF",          ja: "PDFに注釈",          id: "Anotasi PDF",         ru: "Аннотировать PDF",      it: "Annota PDF" },
  "redact":         { ur: "PDF ریڈیکٹ کریں",              es: "Redactar PDF",            ar: "تحرير PDF",              hi: "PDF रेडेक्ट",           fr: "Biffer PDF",             pt: "Redigir PDF",          de: "PDF schwärzen",         zh: "涂黑PDF内容",      ja: "PDFを墨消し",        id: "Redaksi PDF",         ru: "Редактировать PDF",     it: "Oscura PDF" },
  "add-page-numbers":{ ur: "صفحہ نمبر شامل کریں",              es: "Añadir números de página",ar: "إضافة أرقام الصفحات",  hi: "पेज नंबर जोड़ें",      fr: "Ajouter numéros de page",pt: "Adicionar números de página", de: "Seitenzahlen einfügen", zh: "添加页码",        ja: "ページ番号を追加",   id: "Tambah Nomor Halaman",ru: "Добавить номера страниц",it: "Aggiungi numeri di pagina" },
  "remove-pages":   { ur: "صفحات حذف کریں",              es: "Eliminar páginas",        ar: "حذف صفحات",              hi: "पेज हटाएं",             fr: "Supprimer pages",        pt: "Remover páginas",      de: "Seiten entfernen",      zh: "删除页面",         ja: "ページを削除",       id: "Hapus Halaman",       ru: "Удалить страницы",      it: "Rimuovi pagine" },
  "extract-pages":  { ur: "صفحات نکالیں",              es: "Extraer páginas",         ar: "استخراج صفحات",          hi: "पेज निकालें",           fr: "Extraire pages",         pt: "Extrair páginas",      de: "Seiten extrahieren",    zh: "提取页面",         ja: "ページを抽出",       id: "Ekstrak Halaman",     ru: "Извлечь страницы",      it: "Estrai pagine" },
  "reorder-pages":  { ur: "صفحات ترتیب دیں",              es: "Reordenar páginas",       ar: "إعادة ترتيب الصفحات",   hi: "पेज क्रम बदलें",       fr: "Réorganiser pages",      pt: "Reordenar páginas",    de: "Seiten neu anordnen",   zh: "重排页面",         ja: "ページを並べ替え",   id: "Susun Ulang Halaman", ru: "Изменить порядок страниц",it: "Riordina pagine" },
  "translate-pdf":  { ur: "PDF ترجمہ کریں",              es: "Traducir PDF",            ar: "ترجمة PDF",              hi: "PDF अनुवाद करें",       fr: "Traduire PDF",           pt: "Traduzir PDF",         de: "PDF übersetzen",        zh: "翻译PDF",          ja: "PDFを翻訳",          id: "Terjemahkan PDF",     ru: "Перевести PDF",         it: "Traduci PDF" },
  "batch-compress": { ur: "بیچ کمپریس",              es: "Compresión por lotes",    ar: "ضغط دفعي",               hi: "बैच कम्प्रेस",          fr: "Compression par lots",   pt: "Compressão em lote",   de: "Stapelkomprimierung",   zh: "批量压缩",         ja: "バッチ圧縮",         id: "Kompres Massal",      ru: "Пакетное сжатие",       it: "Comprimi in batch" },
  "scan-to-pdf":    { ur: "اسکین سے PDF",              es: "Escanear a PDF",          ar: "مسح إلى PDF",            hi: "स्कैन टू PDF",          fr: "Scanner en PDF",         pt: "Digitalizar para PDF", de: "Scannen zu PDF",        zh: "扫描转PDF",        ja: "スキャンしてPDF",    id: "Pindai ke PDF",       ru: "Сканировать в PDF",     it: "Scansiona in PDF" },
  "pdf-to-pdfa":    { ur: "PDF سے PDF/A",              es: "PDF a PDF/A",             ar: "PDF إلى PDF/A",          hi: "PDF से PDF/A",          fr: "PDF en PDF/A",           pt: "PDF para PDF/A",       de: "PDF zu PDF/A",          zh: "PDF转PDF/A",       ja: "PDFをPDF/Aに変換",   id: "PDF ke PDF/A",        ru: "PDF в PDF/A",           it: "Da PDF a PDF/A" },
  "crop-pdf":       { ur: "PDF کراپ کریں",              es: "Recortar PDF",            ar: "اقتصاص PDF",             hi: "PDF क्रॉप करें",        fr: "Rogner PDF",             pt: "Cortar PDF",           de: "PDF zuschneiden",       zh: "裁剪PDF",          ja: "PDFを切り取り",      id: "Pangkas PDF",         ru: "Обрезать PDF",          it: "Ritaglia PDF" },
  "flatten-pdf":    { ur: "PDF فلیٹن کریں",              es: "Aplanar PDF",             ar: "تسطيح PDF",              hi: "PDF फ्लैट करें",        fr: "Aplatir PDF",            pt: "Achatar PDF",          de: "PDF reduzieren",        zh: "展平PDF",          ja: "PDFをフラット化",    id: "Ratakan PDF",         ru: "Сжать слои PDF",        it: "Appiattisci PDF" },
  "compress-img":   { ur: "تصویر کمپریس کریں",              es: "Comprimir imagen",        ar: "ضغط الصورة",             hi: "इमेज कम्प्रेस",         fr: "Compresser image",       pt: "Comprimir imagem",     de: "Bild komprimieren",     zh: "压缩图片",         ja: "画像を圧縮",         id: "Kompres Gambar",      ru: "Сжать изображение",     it: "Comprimi immagine" },
  "add-watermark":  { ur: "PDF واٹر مارک",              es: "Marca de agua PDF",       ar: "علامة مائية PDF",        hi: "PDF वॉटरमार्क",        fr: "Filigrane PDF",          pt: "Marca d'água PDF",     de: "PDF Wasserzeichen",     zh: "PDF水印",          ja: "PDF透かし",          id: "Watermark PDF",       ru: "Водяной знак PDF",      it: "Filigrana PDF" },
  "annotate-pdf":   { ur: "PDF پر نوٹ لکھیں",              es: "Anotar PDF",              ar: "تعليق على PDF",          hi: "PDF एनोटेट",           fr: "Annoter PDF",            pt: "Anotar PDF",           de: "PDF annotieren",        zh: "注释PDF",          ja: "PDFに注釈",          id: "Anotasi PDF",         ru: "Аннотировать PDF",      it: "Annota PDF" },
  "compare-pdf":    { ur: "PDF موازنہ",              es: "Comparar PDF",            ar: "مقارنة PDF",             hi: "PDF तुलना",             fr: "Comparer PDF",           pt: "Comparar PDF",         de: "PDF vergleichen",       zh: "比较PDF",          ja: "PDFを比較",          id: "Bandingkan PDF",      ru: "Сравнить PDF",          it: "Confronta PDF" },
  "convert-image":  { ur: "تصویر تبدیل کریں",              es: "Convertir imagen",        ar: "تحويل الصورة",           hi: "इमेज कन्वर्ट",          fr: "Convertir image",        pt: "Converter imagem",     de: "Bild konvertieren",     zh: "转换图片",         ja: "画像を変換",         id: "Konversi Gambar",     ru: "Конвертировать фото",   it: "Converti immagine" },
  "crop-image":     { ur: "تصویر کراپ کریں",              es: "Recortar imagen",         ar: "قص الصورة",              hi: "इमेज क्रॉप",           fr: "Rogner image",           pt: "Recortar imagem",      de: "Bild zuschneiden",      zh: "裁剪图片",         ja: "画像を切り取り",     id: "Pangkas Gambar",      ru: "Обрезать изображение",  it: "Ritaglia immagine" },
  "delete-pages":   { ur: "صفحات حذف کریں",              es: "Eliminar páginas",        ar: "حذف صفحات",              hi: "पेज हटाएं",             fr: "Supprimer pages",        pt: "Remover páginas",      de: "Seiten entfernen",      zh: "删除页面",         ja: "ページを削除",       id: "Hapus Halaman",       ru: "Удалить страницы",      it: "Rimuovi pagine" },
  "extract-images": { ur: "تصاویر نکالیں",              es: "Extraer imágenes",        ar: "استخراج الصور",          hi: "इमेज निकालें",          fr: "Extraire images",        pt: "Extrair imagens",      de: "Bilder extrahieren",    zh: "提取图片",         ja: "画像を抽出",         id: "Ekstrak Gambar",      ru: "Извлечь изображения",   it: "Estrai immagini" },
  "extract-text":   { ur: "متن نکالیں",              es: "Extraer texto",            ar: "استخراج النص",           hi: "टेक्स्ट निकालें",       fr: "Extraire texte",         pt: "Extrair texto",        de: "Text extrahieren",      zh: "提取文字",         ja: "テキストを抽出",     id: "Ekstrak Teks",        ru: "Извлечь текст",         it: "Estrai testo" },
  "gif-to-pdf":     { ur: "GIF سے PDF",              es: "GIF a PDF",               ar: "GIF إلى PDF",            hi: "GIF से PDF",            fr: "GIF en PDF",             pt: "GIF para PDF",         de: "GIF zu PDF",            zh: "GIF转PDF",         ja: "GIFをPDFに変換",     id: "GIF ke PDF",          ru: "GIF в PDF",             it: "Da GIF a PDF" },
  "grayscale-pdf":  { ur: "PDF گرے اسکیل",              es: "PDF en escala de grises", ar: "PDF رمادي",              hi: "PDF ग्रेस्केल",         fr: "PDF en niveaux de gris", pt: "PDF em tons de cinza", de: "PDF in Graustufen",     zh: "PDF转灰度",        ja: "PDFをグレー変換",    id: "PDF Skala Abu-abu",   ru: "PDF в оттенках серого", it: "PDF in scala di grigi" },
  "html-to-pdf":    { ur: "HTML سے PDF",              es: "HTML a PDF",              ar: "HTML إلى PDF",           hi: "HTML से PDF",           fr: "HTML en PDF",            pt: "HTML para PDF",        de: "HTML zu PDF",           zh: "HTML转PDF",        ja: "HTMLをPDFに変換",    id: "HTML ke PDF",         ru: "HTML в PDF",            it: "Da HTML a PDF" },
  "pdf-to-powerpoint":{ ur: "PDF سے PowerPoint",              es: "PDF a PowerPoint",        ar: "PDF إلى PowerPoint",     hi: "PDF से PowerPoint",    fr: "PDF en PowerPoint",      pt: "PDF para PowerPoint",  de: "PDF zu PowerPoint",     zh: "PDF转PPT",         ja: "PDFをPPTに変換",     id: "PDF ke PowerPoint",   ru: "PDF в PowerPoint",      it: "Da PDF a PowerPoint" },
  "pdf-viewer":     { ur: "PDF ویور",              es: "Visor PDF",               ar: "عارض PDF",               hi: "PDF व्यूअर",            fr: "Visionneuse PDF",        pt: "Visualizador PDF",     de: "PDF-Viewer",            zh: "PDF查看器",        ja: "PDFビューア",        id: "Penampil PDF",        ru: "Просмотр PDF",          it: "Visualizzatore PDF" },
  "powerpoint-to-pdf":{ ur: "PowerPoint سے PDF",              es: "PowerPoint a PDF",        ar: "PowerPoint إلى PDF",     hi: "PowerPoint से PDF",    fr: "PowerPoint en PDF",      pt: "PowerPoint para PDF",  de: "PowerPoint zu PDF",     zh: "PPT转PDF",         ja: "PPTをPDFに変換",     id: "PowerPoint ke PDF",   ru: "PowerPoint в PDF",      it: "Da PowerPoint a PDF" },
  "protect-pdf":    { ur: "PDF محفوظ کریں",              es: "Proteger PDF",            ar: "حماية PDF",              hi: "PDF सुरक्षित करें",     fr: "Protéger PDF",           pt: "Proteger PDF",         de: "PDF schützen",          zh: "保护PDF",          ja: "PDFを保護",          id: "Lindungi PDF",        ru: "Защитить PDF",          it: "Proteggi PDF" },
  "redact-pdf":     { ur: "PDF ریڈیکٹ کریں",              es: "Redactar PDF",            ar: "تحرير PDF",              hi: "PDF रेडेक्ट",           fr: "Biffer PDF",             pt: "Redigir PDF",          de: "PDF schwärzen",         zh: "涂黑PDF内容",      ja: "PDFを墨消し",        id: "Redaksi PDF",         ru: "Редактировать PDF",     it: "Oscura PDF" },
  "repair-pdf":     { ur: "PDF درست کریں",              es: "Reparar PDF",             ar: "إصلاح PDF",              hi: "PDF रिपेयर",            fr: "Réparer PDF",            pt: "Reparar PDF",          de: "PDF reparieren",        zh: "修复PDF",          ja: "PDFを修復",          id: "Perbaiki PDF",        ru: "Исправить PDF",         it: "Ripara PDF" },
  "resize-image":   { ur: "تصویر کا سائز بدلیں",              es: "Redimensionar imagen",    ar: "تغيير حجم الصورة",      hi: "इमेज रीसाइज़",          fr: "Redimensionner image",   pt: "Redimensionar imagem", de: "Bildgröße ändern",      zh: "调整图片大小",     ja: "画像をリサイズ",     id: "Ubah Ukuran Gambar",  ru: "Изменить размер",       it: "Ridimensiona immagine" },
  "resize-pdf":     { ur: "PDF سائز بدلیں",              es: "Redimensionar PDF",       ar: "تغيير حجم PDF",          hi: "PDF रीसाइज़",           fr: "Redimensionner PDF",     pt: "Redimensionar PDF",    de: "PDF-Größe ändern",      zh: "调整PDF大小",      ja: "PDFをリサイズ",      id: "Ubah Ukuran PDF",     ru: "Изменить размер PDF",   it: "Ridimensiona PDF" },
  "rotate-image":   { ur: "تصویر گھمائیں",              es: "Rotar imagen",            ar: "تدوير الصورة",           hi: "इमेज घुमाएं",           fr: "Pivoter image",          pt: "Girar imagem",         de: "Bild drehen",           zh: "旋转图片",         ja: "画像を回転",         id: "Putar Gambar",        ru: "Повернуть изображение", it: "Ruota immagine" },
  "sign-pdf":       { ur: "PDF سائن کریں",              es: "Firmar PDF",              ar: "توقيع PDF",              hi: "PDF साइन करें",         fr: "Signer PDF",             pt: "Assinar PDF",          de: "PDF unterschreiben",    zh: "签名PDF",          ja: "PDFに署名",          id: "Tanda Tangani PDF",   ru: "Подписать PDF",         it: "Firma PDF" },
  "tiff-to-pdf":    { ur: "TIFF سے PDF",              es: "TIFF a PDF",              ar: "TIFF إلى PDF",           hi: "TIFF से PDF",           fr: "TIFF en PDF",            pt: "TIFF para PDF",        de: "TIFF zu PDF",           zh: "TIFF转PDF",        ja: "TIFFをPDFに変換",    id: "TIFF ke PDF",         ru: "TIFF в PDF",            it: "Da TIFF a PDF" },
  "unlock-pdf":     { ur: "PDF انلاک کریں",              es: "Desbloquear PDF",         ar: "فتح قفل PDF",            hi: "PDF अनलॉक करें",       fr: "Déverrouiller PDF",      pt: "Desbloquear PDF",      de: "PDF entsperren",        zh: "解锁PDF",          ja: "PDFをロック解除",    id: "Buka Kunci PDF",      ru: "Разблокировать PDF",    it: "Sblocca PDF" },
  "webp-to-pdf":    { ur: "WebP سے PDF",              es: "WebP a PDF",              ar: "WebP إلى PDF",           hi: "WebP से PDF",           fr: "WebP en PDF",            pt: "WebP para PDF",        de: "WebP zu PDF",           zh: "WebP转PDF",        ja: "WebPをPDFに変換",    id: "WebP ke PDF",         ru: "WebP в PDF",            it: "Da WebP a PDF" },
};

export function getToolTitle(toolId: string, lang: string, fallback: string): string {
  if (lang === "en") return fallback;
  return TOOL_TITLE_TRANSLATIONS[toolId]?.[lang] || fallback;
}

export const TOOL_DESC_TRANSLATIONS: Record<string, Partial<Record<string, string>>> = {
  "compress": {
    es: "Reduce el tamaño de tu PDF manteniendo la calidad. Elige el nivel de compresión según tus necesidades.",
    ar: "قلل حجم ملف PDF مع الحفاظ على الجودة. اختر مستوى الضغط المناسب لاحتياجاتك.",
    hi: "गुणवत्ता बनाए रखते हुए अपनी PDF का आकार कम करें। अपनी जरूरत के अनुसार कंप्रेशन स्तर चुनें।",
    fr: "Réduisez la taille de votre PDF tout en maintenant la qualité. Choisissez le niveau de compression selon vos besoins.",
    pt: "Reduza o tamanho do seu PDF mantendo a qualidade. Escolha o nível de compressão de acordo com suas necessidades.",
    de: "Reduzieren Sie die Größe Ihrer PDF-Datei bei gleichbleibender Qualität. Wählen Sie den Komprimierungsgrad nach Ihren Bedürfnissen.",
    zh: "在保持质量的同时减小PDF文件大小。根据您的需求选择压缩级别。",
    ja: "品質を維持しながらPDFのファイルサイズを削減します。ニーズに応じた圧縮レベルをお選びください。",
    id: "Kurangi ukuran file PDF sambil mempertahankan kualitas. Pilih tingkat kompresi sesuai kebutuhan Anda.",
    ru: "Уменьшите размер PDF-файла, сохранив качество. Выберите уровень сжатия в соответствии с вашими потребностями.",
    it: "Riduci le dimensioni del tuo PDF mantenendo la qualità. Scegli il livello di compressione in base alle tue esigenze.",
    ur: "معیار برقرار رکھتے ہوئے اپنی PDF کا سائز کم کریں۔ اپنی ضرورت کے مطابق کمپریشن لیول منتخب کریں۔",
  },
  "merge": {
    es: "Combina múltiples archivos PDF en un solo documento. Organiza los archivos en el orden que prefieras antes de unirlos.",
    ar: "ادمج ملفات PDF متعددة في مستند واحد. رتب الملفات بأي ترتيب قبل الدمج.",
    hi: "एकाधिक PDF फ़ाइलों को एक दस्तावेज़ में मिलाएं। मर्ज करने से पहले फ़ाइलों को किसी भी क्रम में व्यवस्थित करें।",
    fr: "Combinez plusieurs fichiers PDF en un seul document. Organisez les fichiers dans l'ordre souhaité avant de les fusionner.",
    pt: "Combine vários arquivos PDF em um único documento. Organize os arquivos em qualquer ordem antes de uni-los.",
    de: "Kombinieren Sie mehrere PDF-Dateien zu einem Dokument. Ordnen Sie die Dateien beliebig an, bevor Sie sie zusammenführen.",
    zh: "将多个PDF文件合并为一个文档。在合并之前以任意顺序排列文件。",
    ja: "複数のPDFファイルを1つのドキュメントに結合します。結合前にファイルを任意の順序で整理できます。",
    id: "Gabungkan beberapa file PDF menjadi satu dokumen. Atur file dalam urutan apa pun sebelum digabungkan.",
    ru: "Объедините несколько PDF-файлов в один документ. Расположите файлы в любом порядке перед объединением.",
    it: "Combina più file PDF in un unico documento. Organizza i file nell'ordine desiderato prima di unirli.",
    ur: "متعدد PDF فائلوں کو ایک دستاویز میں یکجا کریں۔ ملانے سے پہلے فائلوں کو کسی بھی ترتیب میں ترتیب دیں۔",
  },
  "split": {
    es: "Divide tu PDF en páginas separadas o rangos de páginas personalizados.",
    ar: "قسّم ملف PDF إلى صفحات منفصلة أو نطاقات صفحات مخصصة.",
    hi: "अपनी PDF को अलग-अलग पृष्ठों या कस्टम पृष्ठ श्रेणियों में विभाजित करें।",
    fr: "Divisez votre PDF en pages séparées ou en plages de pages personnalisées.",
    pt: "Divida seu PDF em páginas separadas ou intervalos de páginas personalizados.",
    de: "Teilen Sie Ihre PDF in einzelne Seiten oder benutzerdefinierte Seitenbereiche auf.",
    zh: "将您的PDF拆分为单独的页面或自定义页面范围。",
    ja: "PDFを個別のページまたはカスタムページ範囲に分割します。",
    id: "Pisahkan PDF Anda menjadi halaman terpisah atau rentang halaman khusus.",
    ru: "Разделите PDF на отдельные страницы или пользовательские диапазоны страниц.",
    it: "Dividi il tuo PDF in pagine separate o intervalli di pagine personalizzati.",
    ur: "اپنی PDF کو الگ صفحات یا کسٹم صفحہ رینجز میں تقسیم کریں۔",
  },
  "pdf-to-word": {
    es: "Convierte tu PDF a un documento Word editable con alta precisión.",
    ar: "حوّل ملف PDF إلى مستند Word قابل للتعديل بدقة عالية.",
    hi: "अपनी PDF को उच्च सटीकता के साथ संपादन योग्य Word दस्तावेज़ में बदलें।",
    fr: "Convertissez votre PDF en document Word modifiable avec une haute précision.",
    pt: "Converta seu PDF para um documento Word editável com alta precisão.",
    de: "Konvertieren Sie Ihre PDF in ein bearbeitbares Word-Dokument mit hoher Genauigkeit.",
    zh: "将您的PDF高精度转换为可编辑的Word文档。",
    ja: "PDFを高精度で編集可能なWordドキュメントに変換します。",
    id: "Konversi PDF Anda ke dokumen Word yang dapat diedit dengan akurasi tinggi.",
    ru: "Конвертируйте PDF в редактируемый документ Word с высокой точностью.",
    it: "Converti il tuo PDF in un documento Word modificabile con alta precisione.",
    ur: "اپنی PDF کو اعلی درستگی کے ساتھ قابل ترمیم Word دستاویز میں تبدیل کریں۔",
  },
  "jpg-to-pdf": {
    es: "Convierte imágenes JPG a formato PDF de forma rápida y sencilla.",
    ar: "حوّل صور JPG إلى تنسيق PDF بسرعة وسهولة.",
    hi: "JPG छवियों को जल्दी और आसानी से PDF फॉर्मेट में बदलें।",
    fr: "Convertissez des images JPG au format PDF rapidement et facilement.",
    pt: "Converta imagens JPG para o formato PDF de forma rápida e fácil.",
    de: "Konvertieren Sie JPG-Bilder schnell und einfach in das PDF-Format.",
    zh: "快速轻松地将JPG图像转换为PDF格式。",
    ja: "JPG画像を素早く簡単にPDF形式に変換します。",
    id: "Konversi gambar JPG ke format PDF dengan cepat dan mudah.",
    ru: "Быстро и легко конвертируйте JPG-изображения в формат PDF.",
    it: "Converti immagini JPG in formato PDF in modo rapido e semplice.",
    ur: "JPG تصاویر کو جلدی اور آسانی سے PDF فارمیٹ میں تبدیل کریں۔",
  },
  "protect": {
    es: "Añade protección con contraseña a tu archivo PDF para mantenerlo seguro.",
    ar: "أضف حماية بكلمة مرور إلى ملف PDF للحفاظ عليه آمناً.",
    hi: "अपनी PDF फ़ाइल को सुरक्षित रखने के लिए पासवर्ड सुरक्षा जोड़ें।",
    fr: "Ajoutez une protection par mot de passe à votre fichier PDF pour le sécuriser.",
    pt: "Adicione proteção por senha ao seu arquivo PDF para mantê-lo seguro.",
    de: "Fügen Sie Ihrer PDF-Datei einen Passwortschutz hinzu, um sie zu sichern.",
    zh: "为您的PDF文件添加密码保护以确保安全。",
    ja: "PDFファイルにパスワード保護を追加してセキュリティを確保します。",
    id: "Tambahkan perlindungan kata sandi ke file PDF Anda untuk menjaganya tetap aman.",
    ru: "Добавьте защиту паролем к вашему PDF-файлу для обеспечения безопасности.",
    it: "Aggiungi la protezione con password al tuo file PDF per mantenerlo al sicuro.",
    ur: "اپنی PDF فائل کو محفوظ رکھنے کے لیے پاسورڈ پروٹیکشن شامل کریں۔",
  },
  "rotate": {
    es: "Rota las páginas de tu PDF a la orientación correcta.",
    ar: "قم بتدوير صفحات PDF إلى الاتجاه الصحيح.",
    hi: "अपनी PDF के पृष्ठों को सही दिशा में घुमाएं।",
    fr: "Faites pivoter les pages de votre PDF dans la bonne orientation.",
    pt: "Gire as páginas do seu PDF para a orientação correta.",
    de: "Drehen Sie die Seiten Ihrer PDF in die richtige Ausrichtung.",
    zh: "将PDF页面旋转到正确的方向。",
    ja: "PDFページを正しい向きに回転させます。",
    id: "Putar halaman PDF ke orientasi yang benar.",
    ru: "Поверните страницы PDF в правильную ориентацию.",
    it: "Ruota le pagine del tuo PDF nella giusta orientazione.",
    ur: "اپنی PDF کے صفحات کو درست سمت میں گھمائیں۔",
  },
  "pdf-to-jpg": {
    es: "Convierte páginas PDF a imágenes JPG de alta calidad en segundos.",
    ar: "حوّل صفحات PDF إلى صور JPG عالية الجودة في ثوانٍ.",
    hi: "PDF पृष्ठों को सेकंड में उच्च-गुणवत्ता JPG छवियों में बदलें।",
    fr: "Convertissez des pages PDF en images JPG de haute qualité en quelques secondes.",
    pt: "Converta páginas PDF em imagens JPG de alta qualidade em segundos.",
    de: "Konvertieren Sie PDF-Seiten in wenigen Sekunden in hochwertige JPG-Bilder.",
    zh: "在几秒钟内将PDF页面转换为高质量JPG图像。",
    ja: "PDF ページを数秒で高品質な JPG 画像に変換します。",
    id: "Konversi halaman PDF menjadi gambar JPG berkualitas tinggi dalam hitungan detik.",
    ru: "Конвертируйте страницы PDF в высококачественные JPG-изображения за секунды.",
    it: "Converti le pagine PDF in immagini JPG di alta qualità in pochi secondi.",
    ur: "PDF صفحات کو چند سیکنڈوں میں اعلی معیار کی JPG تصاویر میں تبدیل کریں۔",
  },
  "sign-pdf": {
    es: "Añade tu firma a documentos PDF de forma segura y sencilla. Sin necesidad de imprimir.",
    ar: "أضف توقيعك إلى مستندات PDF بأمان وسهولة. بدون حاجة للطباعة.",
    hi: "PDF दस्तावेज़ों में अपना हस्ताक्षर सुरक्षित और आसानी से जोड़ें। प्रिंट करने की जरूरत नहीं।",
    fr: "Ajoutez votre signature à des documents PDF en toute sécurité et facilement. Sans impression.",
    pt: "Adicione sua assinatura a documentos PDF com segurança e facilidade. Sem necessidade de impressão.",
    de: "Fügen Sie Ihre Unterschrift sicher und einfach zu PDF-Dokumenten hinzu. Kein Drucken erforderlich.",
    zh: "安全轻松地为PDF文档添加您的签名，无需打印。",
    ja: "PDF ドキュメントに安全かつ簡単に署名を追加します。印刷不要。",
    id: "Tambahkan tanda tangan Anda ke dokumen PDF dengan aman dan mudah. Tanpa perlu mencetak.",
    ru: "Добавляйте подпись к PDF-документам безопасно и легко. Без необходимости печати.",
    it: "Aggiungi la tua firma ai documenti PDF in modo sicuro e semplice. Senza bisogno di stampare.",
    ur: "PDF دستاویزات میں اپنا دستخط محفوظ اور آسانی سے شامل کریں۔ پرنٹ کی ضرورت نہیں۔",
  },
  "unlock-pdf": {
    es: "Elimina la contraseña de tus archivos PDF protegidos de forma rápida y gratuita.",
    ar: "أزل كلمة المرور من ملفات PDF المحمية بسرعة ومجاناً.",
    hi: "सुरक्षित PDF फ़ाइलों से पासवर्ड जल्दी और मुफ्त में हटाएं।",
    fr: "Supprimez le mot de passe de vos fichiers PDF protégés rapidement et gratuitement.",
    pt: "Remova a senha de seus arquivos PDF protegidos de forma rápida e gratuita.",
    de: "Entfernen Sie das Passwort aus Ihren geschützten PDF-Dateien schnell und kostenlos.",
    zh: "快速免费地从受保护的PDF文件中删除密码。",
    ja: "パスワードで保護された PDF ファイルから素早く無料でパスワードを削除します。",
    id: "Hapus kata sandi dari file PDF yang dilindungi dengan cepat dan gratis.",
    ru: "Быстро и бесплатно удалите пароль из защищённых PDF-файлов.",
    it: "Rimuovi la password dai tuoi file PDF protetti in modo rapido e gratuito.",
    ur: "محفوظ PDF فائلوں سے جلدی اور مفت میں پاسورڈ ہٹائیں۔",
  },
  "word-to-pdf": {
    es: "Convierte tus documentos Word a PDF sin perder el formato ni el diseño.",
    ar: "حوّل مستندات Word إلى PDF دون فقدان التنسيق أو التصميم.",
    hi: "फ़ॉर्मेटिंग या डिज़ाइन खोए बिना Word दस्तावेज़ों को PDF में बदलें।",
    fr: "Convertissez vos documents Word en PDF sans perdre la mise en forme ni la présentation.",
    pt: "Converta seus documentos Word para PDF sem perder a formatação ou o design.",
    de: "Konvertieren Sie Word-Dokumente in PDF, ohne Formatierung oder Design zu verlieren.",
    zh: "将Word文档转换为PDF，不丢失格式或设计。",
    ja: "書式やデザインを失わずにWordドキュメントをPDFに変換します。",
    id: "Konversi dokumen Word ke PDF tanpa kehilangan format atau desain.",
    ru: "Конвертируйте документы Word в PDF без потери форматирования или дизайна.",
    it: "Converti i tuoi documenti Word in PDF senza perdere la formattazione o il design.",
    ur: "فارمیٹنگ یا ڈیزائن کھوئے بغیر Word دستاویزات کو PDF میں تبدیل کریں۔",
  },
  "edit-pdf": {
    es: "Edita el texto, las imágenes y el contenido de tus archivos PDF directamente en el navegador.",
    ar: "حرّر النصوص والصور والمحتوى في ملفات PDF مباشرةً من المتصفح.",
    hi: "ब्राउज़र से सीधे PDF फ़ाइलों में टेक्स्ट, छवियाँ और सामग्री संपादित करें।",
    fr: "Modifiez le texte, les images et le contenu de vos fichiers PDF directement dans le navigateur.",
    pt: "Edite o texto, imagens e conteúdo dos seus arquivos PDF diretamente no navegador.",
    de: "Bearbeiten Sie Text, Bilder und Inhalte Ihrer PDF-Dateien direkt im Browser.",
    zh: "直接在浏览器中编辑PDF文件中的文字、图像和内容。",
    ja: "ブラウザから直接 PDF ファイルのテキスト、画像、コンテンツを編集します。",
    id: "Edit teks, gambar, dan konten file PDF langsung di browser.",
    ru: "Редактируйте текст, изображения и содержимое PDF-файлов прямо в браузере.",
    it: "Modifica testo, immagini e contenuti dei tuoi file PDF direttamente nel browser.",
    ur: "براہ راست براؤزر سے PDF فائلوں میں متن، تصاویر اور مواد ترمیم کریں۔",
  },
  "annotate-pdf": {
    es: "Añade comentarios, resaltados y notas a tus documentos PDF de forma fácil.",
    ar: "أضف تعليقات وتمييزات وملاحظات إلى مستندات PDF بسهولة.",
    hi: "अपने PDF दस्तावेज़ों में टिप्पणियाँ, हाइलाइट और नोट्स आसानी से जोड़ें।",
    fr: "Ajoutez des commentaires, des surlignages et des notes à vos documents PDF facilement.",
    pt: "Adicione comentários, destaques e notas aos seus documentos PDF com facilidade.",
    de: "Fügen Sie Kommentare, Markierungen und Notizen einfach zu Ihren PDF-Dokumenten hinzu.",
    zh: "轻松向PDF文档添加注释、高亮和笔记。",
    ja: "PDF ドキュメントにコメント、ハイライト、メモを簡単に追加します。",
    id: "Tambahkan komentar, sorotan, dan catatan ke dokumen PDF dengan mudah.",
    ru: "Легко добавляйте комментарии, выделения и заметки к PDF-документам.",
    it: "Aggiungi commenti, evidenziazioni e note ai tuoi documenti PDF con facilità.",
    ur: "اپنے PDF دستاویزات میں آسانی سے تبصرے، ہائی لائٹس اور نوٹس شامل کریں۔",
  },
  "png-to-pdf": {
    es: "Convierte imágenes PNG a PDF de forma rápida y gratuita.",
    ar: "حوّل صور PNG إلى PDF بسرعة ومجاناً.",
    hi: "PNG छवियों को जल्दी और मुफ्त में PDF में बदलें।",
    fr: "Convertissez des images PNG en PDF rapidement et gratuitement.",
    pt: "Converta imagens PNG para PDF de forma rápida e gratuita.",
    de: "Konvertieren Sie PNG-Bilder schnell und kostenlos in PDF.",
    zh: "快速免费地将PNG图像转换为PDF。",
    ja: "PNG 画像を素早く無料で PDF に変換します。",
    id: "Konversi gambar PNG ke PDF dengan cepat dan gratis.",
    ru: "Быстро и бесплатно конвертируйте PNG-изображения в PDF.",
    it: "Converti immagini PNG in PDF in modo rapido e gratuito.",
    ur: "PNG تصاویر کو جلدی اور مفت میں PDF میں تبدیل کریں۔",
  },
  "excel-to-pdf": {
    es: "Convierte hojas de cálculo Excel a PDF preservando el formato y el diseño.",
    ar: "حوّل جداول بيانات Excel إلى PDF مع الحفاظ على التنسيق والتصميم.",
    hi: "Excel स्प्रेडशीट को फ़ॉर्मेट और लेआउट बनाए रखते हुए PDF में बदलें।",
    fr: "Convertissez des feuilles de calcul Excel en PDF en préservant la mise en forme et la présentation.",
    pt: "Converta planilhas Excel para PDF preservando a formatação e o layout.",
    de: "Konvertieren Sie Excel-Tabellen in PDF und behalten Sie Formatierung und Layout bei.",
    zh: "将Excel电子表格转换为PDF，保留格式和布局。",
    ja: "書式とレイアウトを保ちながらExcelスプレッドシートをPDFに変換します。",
    id: "Konversi spreadsheet Excel ke PDF dengan mempertahankan format dan tata letak.",
    ru: "Конвертируйте таблицы Excel в PDF, сохраняя форматирование и макет.",
    it: "Converti fogli di calcolo Excel in PDF preservando la formattazione e il layout.",
    ur: "فارمیٹنگ اور لے آؤٹ برقرار رکھتے ہوئے Excel اسپریڈشیٹ کو PDF میں تبدیل کریں۔",
  },
};

export function getToolDesc(toolId: string, lang: string, fallback: string): string {
  if (lang === "en") return fallback;
  return TOOL_DESC_TRANSLATIONS[toolId]?.[lang] || fallback;
}
