export interface Language {
  code: string;
  hreflang: string;
  label: string;
  nativeLabel: string;
  dir: "ltr" | "rtl";
  flag: string;
}

export const SUPPORTED_LANGUAGES: Language[] = [
  { code: "en", hreflang: "en", label: "English", nativeLabel: "English", dir: "ltr", flag: "🇺🇸" },
  { code: "es", hreflang: "es", label: "Spanish", nativeLabel: "Español", dir: "ltr", flag: "🇪🇸" },
  { code: "ar", hreflang: "ar", label: "Arabic", nativeLabel: "العربية", dir: "rtl", flag: "🇸🇦" },
  { code: "hi", hreflang: "hi", label: "Hindi", nativeLabel: "हिंदी", dir: "ltr", flag: "🇮🇳" },
  { code: "fr", hreflang: "fr", label: "French", nativeLabel: "Français", dir: "ltr", flag: "🇫🇷" },
  { code: "pt", hreflang: "pt", label: "Portuguese", nativeLabel: "Português", dir: "ltr", flag: "🇧🇷" },
];

export const LANG_CODES = SUPPORTED_LANGUAGES.map(l => l.code);
export const NON_DEFAULT_LANG_CODES = LANG_CODES.filter(c => c !== "en");

export function getLang(code: string): Language {
  return SUPPORTED_LANGUAGES.find(l => l.code === code) || SUPPORTED_LANGUAGES[0];
}

export function detectBrowserLang(): string {
  const nav = typeof navigator !== "undefined" ? navigator : null;
  if (!nav) return "en";
  const preferred = (nav.language || "en").split("-")[0].toLowerCase();
  return NON_DEFAULT_LANG_CODES.includes(preferred) ? preferred : "en";
}

export function getLangFromPath(pathname: string): { lang: string; basePath: string } {
  const match = pathname.match(/^\/(es|ar|hi|fr|pt)(\/.*)?$/);
  if (match) {
    return { lang: match[1], basePath: match[2] || "/" };
  }
  return { lang: "en", basePath: pathname };
}

export function buildLangPath(lang: string, basePath: string): string {
  if (lang === "en") return basePath;
  const normalizedBase = basePath.startsWith("/") ? basePath : `/${basePath}`;
  return `/${lang}${normalizedBase === "/" ? "" : normalizedBase}`;
}

export const UI_TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    home: "Home",
    allTools: "All Tools",
    blog: "Blog",
    pdfToWord: "PDF to Word",
    merge: "Merge PDF",
    compress: "Compress",
    languageSwitcher: "Language",
    bannerText: "This page is available in",
    bannerSwitch: "Switch to",
    bannerDismiss: "Dismiss",
    uploadYourFiles: "Upload Your Files",
    dropFilesHere: "Drop your files here!",
    releaseToUpload: "Release to upload",
    tapToSelectFile: "Tap to select your file",
    tapToSelectFiles: "Tap to select up to {n} files",
    selectFile: "Select File",
    selectFiles: "Select Files",
    selectedFile: "Selected File",
    selectedFiles: "Selected Files ({n}/{max})",
    addMore: "Add More",
    clearAll: "Clear All",
    secure: "Secure",
    fast: "Fast",
    free: "Free",
    hundredFree: "100% Free",
    noLimits: "No Limits",
    noHiddenCosts: "No hidden costs",
    sslEncrypted: "SSL encrypted",
    cloudPowered: "Cloud powered",
    unlimitedUse: "Unlimited use",
    popularTools: "Popular Tools",
    menu: "Menu",
    openMenu: "Open menu",
    convertFromPdf: "Convert from PDF",
    convertToPdf: "Convert to PDF",
    editPdf: "Edit PDF",
    utilityTools: "Utility Tools",
    compressPdf: "Compress PDF",
    freeToolsCount: "43+ Free PDF Tools",
  },
  es: {
    home: "Inicio",
    allTools: "Todas las herramientas",
    blog: "Blog",
    pdfToWord: "PDF a Word",
    merge: "Unir PDF",
    compress: "Comprimir",
    languageSwitcher: "Idioma",
    bannerText: "Esta página está disponible en",
    bannerSwitch: "Cambiar a",
    bannerDismiss: "Cerrar",
    uploadYourFiles: "Sube tus archivos",
    dropFilesHere: "¡Suelta tus archivos aquí!",
    releaseToUpload: "Suelta para subir",
    tapToSelectFile: "Toca para seleccionar tu archivo",
    tapToSelectFiles: "Toca para seleccionar hasta {n} archivos",
    selectFile: "Seleccionar archivo",
    selectFiles: "Seleccionar archivos",
    selectedFile: "Archivo seleccionado",
    selectedFiles: "Archivos seleccionados ({n}/{max})",
    addMore: "Añadir más",
    clearAll: "Limpiar todo",
    secure: "Seguro",
    fast: "Rápido",
    free: "Gratis",
    hundredFree: "100% Gratis",
    noLimits: "Sin límites",
    noHiddenCosts: "Sin costos ocultos",
    sslEncrypted: "Cifrado SSL",
    cloudPowered: "Nube potente",
    unlimitedUse: "Uso ilimitado",
    popularTools: "Herramientas populares",
    menu: "Menú",
    openMenu: "Abrir menú",
    convertFromPdf: "Convertir desde PDF",
    convertToPdf: "Convertir a PDF",
    editPdf: "Editar PDF",
    utilityTools: "Herramientas de utilidad",
    compressPdf: "Comprimir PDF",
    freeToolsCount: "43+ herramientas PDF gratis",
  },
  ar: {
    home: "الرئيسية",
    allTools: "جميع الأدوات",
    blog: "المدونة",
    pdfToWord: "PDF إلى Word",
    merge: "دمج PDF",
    compress: "ضغط",
    languageSwitcher: "اللغة",
    bannerText: "هذه الصفحة متاحة باللغة",
    bannerSwitch: "التبديل إلى",
    bannerDismiss: "إغلاق",
    uploadYourFiles: "قم برفع ملفاتك",
    dropFilesHere: "أسقط ملفاتك هنا!",
    releaseToUpload: "أطلق للرفع",
    tapToSelectFile: "انقر لاختيار ملفك",
    tapToSelectFiles: "انقر لاختيار حتى {n} ملفات",
    selectFile: "اختر ملفاً",
    selectFiles: "اختر ملفات",
    selectedFile: "الملف المختار",
    selectedFiles: "الملفات المختارة ({n}/{max})",
    addMore: "أضف المزيد",
    clearAll: "مسح الكل",
    secure: "آمن",
    fast: "سريع",
    free: "مجاني",
    hundredFree: "100% مجاني",
    noLimits: "بلا حدود",
    noHiddenCosts: "لا تكاليف خفية",
    sslEncrypted: "مشفر بـ SSL",
    cloudPowered: "مدعوم بالسحابة",
    unlimitedUse: "استخدام غير محدود",
    popularTools: "الأدوات الشائعة",
    menu: "القائمة",
    openMenu: "فتح القائمة",
    convertFromPdf: "التحويل من PDF",
    convertToPdf: "التحويل إلى PDF",
    editPdf: "تعديل PDF",
    utilityTools: "أدوات المرافق",
    compressPdf: "ضغط PDF",
    freeToolsCount: "أكثر من 43 أداة PDF مجانية",
  },
  hi: {
    home: "होम",
    allTools: "सभी टूल्स",
    blog: "ब्लॉग",
    pdfToWord: "PDF से Word",
    merge: "PDF जोड़ें",
    compress: "कम्प्रेस",
    languageSwitcher: "भाषा",
    bannerText: "यह पृष्ठ उपलब्ध है",
    bannerSwitch: "स्विच करें",
    bannerDismiss: "बंद करें",
    uploadYourFiles: "अपनी फ़ाइलें अपलोड करें",
    dropFilesHere: "यहाँ फ़ाइलें छोड़ें!",
    releaseToUpload: "अपलोड करने के लिए छोड़ें",
    tapToSelectFile: "फ़ाइल चुनने के लिए टैप करें",
    tapToSelectFiles: "{n} फ़ाइलें चुनने के लिए टैप करें",
    selectFile: "फ़ाइल चुनें",
    selectFiles: "फ़ाइलें चुनें",
    selectedFile: "चुनी गई फ़ाइल",
    selectedFiles: "चुनी गई फ़ाइलें ({n}/{max})",
    addMore: "और जोड़ें",
    clearAll: "सब हटाएं",
    secure: "सुरक्षित",
    fast: "तेज़",
    free: "मुफ़्त",
    hundredFree: "100% मुफ़्त",
    noLimits: "कोई सीमा नहीं",
    noHiddenCosts: "कोई छुपी लागत नहीं",
    sslEncrypted: "SSL एन्क्रिप्टेड",
    cloudPowered: "क्लाउड पावर्ड",
    unlimitedUse: "असीमित उपयोग",
    popularTools: "लोकप्रिय टूल्स",
    menu: "मेनू",
    openMenu: "मेनू खोलें",
    convertFromPdf: "PDF से कन्वर्ट करें",
    convertToPdf: "PDF में कन्वर्ट करें",
    editPdf: "PDF संपादित करें",
    utilityTools: "उपयोगिता टूल्स",
    compressPdf: "PDF कम्प्रेस",
    freeToolsCount: "43+ मुफ़्त PDF टूल्स",
  },
  fr: {
    home: "Accueil",
    allTools: "Tous les outils",
    blog: "Blog",
    pdfToWord: "PDF en Word",
    merge: "Fusionner PDF",
    compress: "Compresser",
    languageSwitcher: "Langue",
    bannerText: "Cette page est disponible en",
    bannerSwitch: "Passer à",
    bannerDismiss: "Fermer",
    uploadYourFiles: "Téléchargez vos fichiers",
    dropFilesHere: "Déposez vos fichiers ici !",
    releaseToUpload: "Relâchez pour télécharger",
    tapToSelectFile: "Touchez pour sélectionner votre fichier",
    tapToSelectFiles: "Touchez pour sélectionner jusqu'à {n} fichiers",
    selectFile: "Sélectionner un fichier",
    selectFiles: "Sélectionner des fichiers",
    selectedFile: "Fichier sélectionné",
    selectedFiles: "Fichiers sélectionnés ({n}/{max})",
    addMore: "Ajouter plus",
    clearAll: "Tout effacer",
    secure: "Sécurisé",
    fast: "Rapide",
    free: "Gratuit",
    hundredFree: "100% Gratuit",
    noLimits: "Sans limites",
    noHiddenCosts: "Aucun frais caché",
    sslEncrypted: "Chiffrement SSL",
    cloudPowered: "Cloud puissant",
    unlimitedUse: "Utilisation illimitée",
    popularTools: "Outils populaires",
    menu: "Menu",
    openMenu: "Ouvrir le menu",
    convertFromPdf: "Convertir depuis PDF",
    convertToPdf: "Convertir en PDF",
    editPdf: "Modifier PDF",
    utilityTools: "Outils utilitaires",
    compressPdf: "Compresser PDF",
    freeToolsCount: "43+ outils PDF gratuits",
  },
  pt: {
    home: "Início",
    allTools: "Todas as ferramentas",
    blog: "Blog",
    pdfToWord: "PDF para Word",
    merge: "Unir PDF",
    compress: "Comprimir",
    languageSwitcher: "Idioma",
    bannerText: "Esta página está disponível em",
    bannerSwitch: "Mudar para",
    bannerDismiss: "Fechar",
    uploadYourFiles: "Envie seus arquivos",
    dropFilesHere: "Solte seus arquivos aqui!",
    releaseToUpload: "Solte para enviar",
    tapToSelectFile: "Toque para selecionar seu arquivo",
    tapToSelectFiles: "Toque para selecionar até {n} arquivos",
    selectFile: "Selecionar arquivo",
    selectFiles: "Selecionar arquivos",
    selectedFile: "Arquivo selecionado",
    selectedFiles: "Arquivos selecionados ({n}/{max})",
    addMore: "Adicionar mais",
    clearAll: "Limpar tudo",
    secure: "Seguro",
    fast: "Rápido",
    free: "Grátis",
    hundredFree: "100% Grátis",
    noLimits: "Sem limites",
    noHiddenCosts: "Sem custos ocultos",
    sslEncrypted: "Criptografia SSL",
    cloudPowered: "Cloud potente",
    unlimitedUse: "Uso ilimitado",
    popularTools: "Ferramentas populares",
    menu: "Menu",
    openMenu: "Abrir menu",
    convertFromPdf: "Converter de PDF",
    convertToPdf: "Converter para PDF",
    editPdf: "Editar PDF",
    utilityTools: "Ferramentas utilitárias",
    compressPdf: "Comprimir PDF",
    freeToolsCount: "43+ ferramentas PDF grátis",
  },
};

export function t(lang: string, key: string): string {
  return UI_TRANSLATIONS[lang]?.[key] || UI_TRANSLATIONS["en"][key] || key;
}

export function tFormat(lang: string, key: string, vars: Record<string, string | number>): string {
  let str = t(lang, key);
  for (const [k, v] of Object.entries(vars)) {
    str = str.replace(`{${k}}`, String(v));
  }
  return str;
}
